// ============================================================================
// --- IRONCORE MASTER ENGINE (UNIFICADO, BLINDADO Y COMPLETO) ---
// ============================================================================

// 1. ESTADO GLOBAL Y UTILIDADES
let totalCalorias = 0, totalProt = 0, totalCarb = 0, totalGrasa = 0, totalAgua = 0, totalQuemadas = 0, userStreak = 1;
let metaCalorias = 2500, metaProt = 165, metaCarb = 275, metaGrasa = 69;
let currentRankName = "Ashigaru";
let userProfile = { perfilCompleto: false, nickname: "", genero: "M", edad: 25, peso: 75, altura: 175, metaObj: 0, actividad: 1.55, avatarStyle: "bottts" };

window.getTodayKey = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
window.showToast = msg => { const t = document.getElementById('toast-notif'); if(t){ t.innerHTML=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),3500); } };

window.guardarEstadoNube = async () => { 
  if(!window.db || !window.currentUser) return; 
  try { await window.setDoc(window.doc(window.db, "users", window.currentUser.uid), { calorias: totalCalorias, proteina: totalProt, carbos: totalCarb, grasa: totalGrasa, agua: totalAgua, quemadas: totalQuemadas, metaCal: metaCalorias, metaProt: metaProt, metaCarb: metaCarb, metaGrasa: metaGrasa, streak: userStreak, ultimaFecha: localStorage.getItem('ic_ultima_fecha'), currentRankName, ...userProfile }, { merge: true }); } catch(e) {} 
};

window.actualizarUIHeader = () => { const dn = document.getElementById('user-display-name'); if(dn) dn.innerText = userProfile.nickname.toUpperCase(); const wb = document.getElementById('user-welcome-box'); if(wb) wb.style.display = 'flex'; };

window.verificarCambioDeDia = () => { const hoy = new Date().toDateString(); const ult = localStorage.getItem('ic_ultima_fecha'); if (!ult) localStorage.setItem('ic_ultima_fecha', hoy); else if (ult !== hoy) { totalCalorias=0; totalProt=0; totalCarb=0; totalGrasa=0; totalAgua=0; totalQuemadas=0; userStreak++; localStorage.setItem('ic_ultima_fecha', hoy); window.guardarEstadoNube(); window.showToast('🌙 Nuevo día. ¡Racha incrementada!'); } const st = document.getElementById('header-streak'); if(st) st.innerText = `🔥 Racha: ${userStreak} días`; };

window.reiniciarDiaActual = () => { if(confirm("¿Reiniciar balance de hoy?")) { totalCalorias=0; totalProt=0; totalCarb=0; totalGrasa=0; totalAgua=0; totalQuemadas=0; window.guardarEstadoNube(); window.actualizarDashboard(); window.actualizarAguaUI(); const lc = document.getElementById('lista-comidas'); if(lc) lc.innerHTML = ''; window.showToast('🔄 Restablecido.'); } };

// 2. DASHBOARD Y AGUA
window.actualizarDashboard = () => { 
  const dashContainer = document.getElementById('page-dashboard'); if(!dashContainer) return;
  let dashUI = document.getElementById('iron-dash-ui-advanced');
  if(!dashUI) { document.querySelectorAll('.card-main, .macros, .water-card, .coach-tip, #btn-checkin, #calorias-total, .energy-breakdown, .chart-container').forEach(el => el.style.display = 'none'); dashUI = document.createElement('div'); dashUI.id = 'iron-dash-ui-advanced'; dashContainer.insertBefore(dashUI, dashContainer.firstChild); }
  const calNetas = Math.max(0, totalCalorias - totalQuemadas); const calPct = Math.min(100, (calNetas / metaCalorias) * 100) || 0;
  const prPct = Math.min(100, (totalProt/metaProt)*100) || 0; const cbPct = Math.min(100, (totalCarb/metaCarb)*100) || 0; const grPct = Math.min(100, (totalGrasa/metaGrasa)*100) || 0;
  const calColor = calNetas > metaCalorias ? '#ff3366' : '#00e5ff';
  let tmb = userProfile.genero === 'M' ? (10 * userProfile.peso) + (6.25 * userProfile.altura) - (5 * userProfile.edad) + 5 : (10 * userProfile.peso) + (6.25 * userProfile.altura) - (5 * userProfile.edad) - 161;

  dashUI.innerHTML = `
    <button class="btn btn-warning" style="width:100%; margin-bottom: 20px; font-size:13px; text-transform:uppercase;" onclick="window.openSheet('sheet-checkin')">📈 Registrar Peso de Hoy</button>
    <div class="card" style="padding:25px 20px; position:relative;">
      <div style="display:flex; justify-content:space-between; margin-bottom:25px;"><h3 style="margin:0; font-size:15px; color:#fff; text-transform:uppercase; letter-spacing:1px;">Flujo de Energía</h3><button class="btn-clear-history" style="font-size:10px; color:var(--primary); border:1px solid var(--primary); background:rgba(0,229,255,0.1);" onclick="window.reiniciarDiaActual()">🔄 Reiniciar</button></div>
      <div class="energy-ring" style="--pct: ${calPct}%; --primary: ${calColor};"><div class="energy-ring-content"><span style="font-size:40px; font-weight:900; color:${calColor}; text-shadow:0 0 15px rgba(0,229,255,0.5); display:block; line-height:1;">${calNetas}</span><span style="font-size:10px; color:#9ca3af; text-transform:uppercase; font-weight:800; letter-spacing:1px; display:block; margin-top:5px;">Kcal Netas</span></div></div>
      <div style="display:flex; justify-content:space-around; text-align:center; margin-bottom:20px; border-top:1px dashed rgba(255,255,255,0.1); padding-top:20px;"><div><span style="font-size:10px; color:#9ca3af; font-weight:800; display:block; margin-bottom:4px;">CONSUMO</span><b style="color:#00e5ff; font-size:16px;">+${totalCalorias}</b></div><div><span style="font-size:10px; color:#9ca3af; font-weight:800; display:block; margin-bottom:4px;">QUEMADO</span><b style="color:#ffaa00; font-size:16px;">🔥-${totalQuemadas}</b></div><div><span style="font-size:10px; color:#9ca3af; font-weight:800; display:block; margin-bottom:4px;">META DÍA</span><b style="color:#fff; font-size:16px;">${metaCalorias}</b></div></div>
      <div style="text-align:center; margin-bottom:20px; font-size:11px; color:#9ca3af; font-weight:bold;">Metabolismo Basal (TMB): <span style="color:#fff;">${Math.round(tmb)} kcal/día</span></div>
      <div class="stats-grid" style="margin-top:0;"><div class="stat-panel"><div class="stat-title">Proteína</div><div class="stat-value" style="font-size:18px;">${totalProt}<small style="font-size:10px; color:var(--text-muted);">/${metaProt}g</small></div><div class="macro-progress-container"><div class="macro-progress-fill" style="width:${prPct}%; background:#ff3366; box-shadow: 0 0 10px #ff3366;"></div></div></div><div class="stat-panel"><div class="stat-title">Carbos</div><div class="stat-value" style="font-size:18px;">${totalCarb}<small style="font-size:10px; color:var(--text-muted);">/${metaCarb}g</small></div><div class="macro-progress-container"><div class="macro-progress-fill" style="width:${cbPct}%; background:#00e5ff; box-shadow: 0 0 10px #00e5ff;"></div></div></div><div class="stat-panel stat-panel-full"><div class="stat-title">Grasas</div><div class="stat-value" style="font-size:18px;">${totalGrasa}<small style="font-size:10px; color:var(--text-muted);">/${metaGrasa}g</small></div><div class="macro-progress-container"><div class="macro-progress-fill" style="width:${grPct}%; background:#ffaa00; box-shadow: 0 0 10px #ffaa00;"></div></div></div></div>
    </div>
    <div class="card" style="padding:20px; margin-top:20px;"><div style="display:flex; justify-content:space-between; margin-bottom:15px;"><h3 style="margin:0; font-size:14px; color:#fff; text-transform:uppercase; letter-spacing:1px;">💧 Hidratación</h3><button style="background:rgba(0,229,255,0.1); border:1px solid #00e5ff; border-radius:6px; color:#00e5ff; font-size:11px; font-weight:bold; cursor:pointer; padding:4px 8px;" onclick="window.resetAgua()">Reset</button></div><div style="display:flex; align-items:center; gap:15px;"><div style="flex:1;"><div class="stat-value" style="font-size:20px; color:#00e5ff;">${totalAgua/1000}L <span style="font-size:10px; color:#9ca3af;">/ 3.0L</span></div><div class="macro-progress-container" style="height:12px;"><div class="macro-progress-fill" id="water-fill-bar" style="width:${Math.min(100, (totalAgua/3000)*100)}%; background:#00e5ff; box-shadow: 0 0 10px #00e5ff;"></div></div></div><button class="btn btn-primary" style="width:auto; margin:0; padding:15px; font-size:12px;" onclick="window.agregarAgua(500)">+ 500ml</button></div></div>
  `;
};

window.actualizarAguaUI = () => { const meta = 3000; let pct = Math.min(100, Math.round((totalAgua/meta)*100)); const wb = document.getElementById('water-fill-bar'); if(wb) wb.style.width = `${pct}%`; window.guardarEstadoNube(); };
window.agregarAgua = ml => { totalAgua += ml; window.actualizarAguaUI(); window.actualizarDashboard(); window.showToast(`💧 +${ml} ml añadidos.`); }; 
window.resetAgua = () => { totalAgua = 0; window.actualizarAguaUI(); window.actualizarDashboard(); window.showToast(`🔄 Hidratación reiniciada.`); };

// 3. FIREBASE INIT E IMPORTACIONES
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, collection, addDoc, getDocs, deleteDoc, query, orderBy, limit, where } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";

const app = initializeApp({ apiKey: "AIzaSyAK3QRT5FOqe9q-hxI3NWtTvZT2uGGLCTU", authDomain: "ironcoreapp-66a12.firebaseapp.com", projectId: "ironcoreapp-66a12", storageBucket: "ironcoreapp-66a12.firebasestorage.app", messagingSenderId: "673931910641", appId: "1:673931910641:web:eb3d5a830cbcd31fc6f850" });
window.auth = getAuth(app); window.db = getFirestore(app);
window.doc = doc; window.setDoc = setDoc; window.getDoc = getDoc; window.collection = collection; window.addDoc = addDoc; window.getDocs = getDocs; window.deleteDoc = deleteDoc; window.query = query; window.orderBy = orderBy; window.limit = limit; window.where = where;

// 4. AUTENTICACIÓN Y LISTENERS
document.addEventListener('DOMContentLoaded', () => {
  const loginBtn = document.getElementById('btn-google-login');
  if (loginBtn) {
    loginBtn.onclick = async () => {
      window.showToast('🔄 Conectando con Google...');
      const provider = new GoogleAuthProvider();
      provider.setCustomParameters({ prompt: 'select_account' });
      try { await signInWithPopup(window.auth, provider); } catch (error) { await signInWithRedirect(window.auth, provider); }
    };
  }
});

onAuthStateChanged(window.auth, async (user) => {
  if (user) { 
    window.currentUser = user; 
    const authScn = document.getElementById('auth-screen'); if(authScn) authScn.style.display = 'none'; 
    await window.cargarDatosDesdeNube(user.uid); 
    window.iniciarNotificacionesEnVivo(user.uid); 
  } else { 
    window.currentUser = null; 
    const authScn = document.getElementById('auth-screen'); if(authScn) authScn.style.display = 'flex'; 
    const wb = document.getElementById('user-welcome-box'); if(wb) wb.style.display = 'none'; 
  }
});

// 5. NAVEGACIÓN Y BOTTOM SHEETS
document.querySelectorAll('.nav-item').forEach(btn => { btn.addEventListener('click', () => { document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active')); document.querySelectorAll('.page').forEach(p => { p.classList.remove('active'); p.style.display = 'none'; }); btn.classList.add('active'); const tgt = document.getElementById(btn.getAttribute('data-target')); if(tgt) { tgt.classList.add('active'); tgt.style.display = 'block'; } if(btn.getAttribute('data-target') === 'page-social') window.cargarModuloSocialCompleto(); }); });
document.querySelectorAll('.tab-btn-diet, .tab-btn-train').forEach(btn => { btn.addEventListener('click', () => { const group = btn.className.split(' ')[0]; document.querySelectorAll(`.${group}`).forEach(t => t.classList.remove('active')); document.querySelectorAll(`.${btn.getAttribute('data-tab').startsWith('tab-r')||btn.getAttribute('data-tab').startsWith('tab-p')?group.replace('btn','sub'):group.replace('btn','sub')}`).forEach(s => s.style.display = 'none'); btn.classList.add('active'); document.getElementById(btn.getAttribute('data-tab')).style.display = 'block'; if(btn.getAttribute('data-tab') === 'tab-leaderboard') window.cargarLeaderboard(); }); });

const overlay = document.getElementById('sheet-overlay');
window.openSheet = id => { const s = document.getElementById(id); if(overlay) overlay.style.display = 'block'; if(s) { s.classList.add('open'); setTimeout(() => s.style.bottom = '0', 10); window.currentActiveSheet = s; } };
window.closeSheet = () => { document.querySelectorAll('.bottom-sheet').forEach(s => { s.style.bottom = '-100%'; s.classList.remove('open'); }); if(overlay) overlay.style.display = 'none'; window.currentActiveSheet = null; };
if(overlay) overlay.addEventListener('click', window.closeSheet);

// 6. PERFIL Y GRÁFICOS
window.actualizarUIPerfil = () => { 
  const profPage = document.getElementById('profile-dynamic-root'); if(!profPage) return;
  let labelMeta = userProfile.metaObj === -500 ? "Déficit Agresivo" : userProfile.metaObj === -300 ? "Definición" : userProfile.metaObj === 300 ? "Volumen" : "Mantenimiento";
  let avatarUrl = window.generarAvatarPorRango(userProfile.nickname, currentRankName, userProfile.avatarStyle);
  profPage.innerHTML = `
    <div class="card" style="text-align: center; position: relative;">
      <div style="position:relative; display:inline-block;"><img src="${avatarUrl}" style="width: 100px; height: 100px; border-radius: 50%; border: 3px solid var(--primary); margin-bottom: 10px; object-fit: cover; background: #1a2130; box-shadow: 0 0 20px rgba(0,229,255,0.4);"><button onclick="window.cambiarEstiloAvatar()" style="position:absolute; bottom:10px; right:-10px; background:var(--primary); color:#000; border:none; border-radius:50%; width:35px; height:35px; font-size:18px; cursor:pointer; box-shadow:0 2px 10px rgba(0,0,0,0.8); z-index:10; transition:0.2s;">🎲</button></div>
      <h2 style="margin: 0; color: #fff; font-size: 26px; text-transform: uppercase; font-weight:900; letter-spacing:1px;">${userProfile.nickname}</h2>
      <div style="color:var(--accent); font-size:13px; font-weight:900; margin-top:5px; text-transform:uppercase; letter-spacing:2px;">Rango: ${currentRankName}</div>
      <span style="display:inline-block; padding: 6px 12px; background: rgba(0,229,255,0.1); border: 1px solid rgba(0,229,255,0.3); color: var(--primary); font-size: 11px; font-weight:800; border-radius: 12px; margin-top: 15px; text-transform: uppercase;">Meta: ${labelMeta}</span>
      <div class="stats-grid" style="margin-top: 25px; text-align: left;"><div class="stat-panel"><div class="stat-title">Peso</div><div class="stat-value" style="font-size:18px;">${userProfile.peso} <small style="font-size:10px; color:var(--text-muted);">kg</small></div></div><div class="stat-panel"><div class="stat-title">Altura</div><div class="stat-value" style="font-size:18px;">${userProfile.altura} <small style="font-size:10px; color:var(--text-muted);">cm</small></div></div><div class="stat-panel"><div class="stat-title">Edad</div><div class="stat-value" style="font-size:18px;">${userProfile.edad} <small style="font-size:10px; color:var(--text-muted);">años</small></div></div><div class="stat-panel"><div class="stat-title">Género</div><div class="stat-value" style="font-size:18px;">${userProfile.genero === 'M' ? 'Hombre' : 'Mujer'}</div></div></div>
      <div style="display:flex; gap:10px; margin-top:25px;"><button class="btn btn-primary" style="flex:2;" onclick="window.abrirOnboarding(true)">⚙️ Modificar Parámetros</button><button class="btn btn-secondary" style="flex:1; border-color:#ff3366; color:#ff3366;" onclick="window.cerrarSesionApp()">Salir</button></div>
    </div><div id="wrapper-profile-chart-inj"></div>`;
};

let profileChartInstance = null;
window.dibujarGraficoPerfil = (historialPesos) => {
  const chartWrapper = document.getElementById('wrapper-profile-chart-inj'); if(!chartWrapper) return;
  chartWrapper.innerHTML = `<div class="card" style="padding: 20px;"><h4 style="font-size: 13px; color: var(--primary); text-transform: uppercase; font-weight: 900; letter-spacing: 1px; margin: 0 0 20px 0;">📈 Proyección vs Realidad</h4><div style="height: 250px; width: 100%;"><canvas id="profile-chart-canvas-inj"></canvas></div></div>`;
  const ctx = document.getElementById('profile-chart-canvas-inj'); if(!ctx) return;
  if(profileChartInstance) profileChartInstance.destroy();
  const labels = historialPesos.map(item => item.fecha.split('-').slice(1).join('/')).reverse(); const realData = historialPesos.map(item => item.peso).reverse();
  let projectionData = [];
  if(realData.length > 0) { let startWeight = realData[0]; let dailyChange = userProfile.metaObj === -500 ? -0.1 : userProfile.metaObj === -300 ? -0.04 : userProfile.metaObj === 300 ? 0.04 : 0; projectionData = labels.map((_, i) => parseFloat((startWeight + (dailyChange * i * 3)).toFixed(1))); }
  profileChartInstance = new Chart(ctx.getContext('2d'), { type: 'line', data: { labels: labels, datasets: [ { label: 'Peso Real', data: realData, borderColor: '#00e5ff', backgroundColor: 'rgba(0, 229, 255, 0.2)', borderWidth: 4, fill: true, tension: 0.4, pointBackgroundColor: '#fff', pointRadius: 5, pointBorderColor: '#00e5ff', pointBorderWidth: 2 }, { label: 'Ruta Ideal', data: projectionData, borderColor: 'rgba(255, 170, 0, 0.8)', borderDash: [6, 6], borderWidth: 2, fill: false, pointRadius: 0 } ] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: true, labels: { color: '#fff', font:{size:11, family:'Montserrat'} } } }, scales: { y: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks:{color:'#9ca3af'} }, x: { grid: { display: false }, ticks:{color:'#9ca3af'} } } } });
};

// 7. CARGA DESDE LA NUBE (CONEXIÓN SEGURA)
window.cargarDatosDesdeNube = async (uid) => {
  if(!window.db) return; const docSnap = await window.getDoc(window.doc(window.db, "users", uid)); 
  if (docSnap.exists()) { 
    const d = docSnap.data(); totalCalorias = d.calorias || 0; totalProt = d.proteina || 0; totalCarb = d.carbos || 0; totalGrasa = d.grasa || 0; totalAgua = d.agua || 0; totalQuemadas = d.quemadas || 0; metaCalorias = d.metaCal || 2500; metaProt = d.metaProt || 165; metaCarb = d.metaCarb || 275; metaGrasa = d.metaGrasa || 69; userStreak = d.streak || 1; userProfile.perfilCompleto = d.perfilCompleto || false; userProfile.nickname = d.nickname || ""; userProfile.genero = d.genero || "M"; userProfile.edad = d.edad || 25; userProfile.peso = d.peso || 75; userProfile.altura = d.altura || 175; userProfile.metaObj = d.metaObj !== undefined ? d.metaObj : 0; userProfile.actividad = d.actividad || 1.55; currentRankName = d.currentRankName || "Ashigaru"; userProfile.avatarStyle = d.avatarStyle || "bottts"; 
    if(!d.nickname_lower && userProfile.nickname) { userProfile.nickname_lower = userProfile.nickname.toLowerCase(); window.guardarEstadoNube(); } 
  } 
  if(!userProfile.perfilCompleto) { window.abrirOnboarding(false); } else { window.actualizarUIHeader(); window.actualizarUIPerfil(); } 
  window.verificarCambioDeDia(); window.actualizarDashboard(); window.actualizarAguaUI(); 
  await window.cargarRegistrosDelDia(uid); await window.cargarHistorialYCheckins(uid); await window.recuperarPlanesGuardados();
};

// 8. ENTRENAMIENTO Y CARDIO
let currentWorkoutRoutine = []; let activeTimers = {}; 
document.getElementById('btn-generar-rutina')?.addEventListener('click', () => {
  if(exercisesDB.length === 0) { window.showToast('⚠️ Sincronizando ejercicios...'); return; }
  const equip = document.getElementById('train-equip')?.value || 'gimnasio'; const focus = document.getElementById('train-focus')?.value || 'fullbody'; currentWorkoutRoutine = [];
  const checkWarm = document.getElementById('check-warmup'); if(checkWarm && checkWarm.checked) { currentWorkoutRoutine.push({ id: 'warmup', nombre: '🔥 Activación Core/Articular', grupo: 'cardio', musculoPrincipal: 'Total', equipamiento: ['corporal'], tips: '5 a 10 min movilidad.', imagen: 'https://dummyimage.com/400x400/111827/ffaa00&text=CALENTAR', loggedSets: [], isPhase: true }); }
  const getRandomEx = (gReq) => { const v = exercisesDB.filter(ex => ex.grupo?.toLowerCase() === gReq.toLowerCase() && (Array.isArray(ex.equipamiento) ? ex.equipamiento.some(eq => eq.toLowerCase().includes(equip.toLowerCase())) : true)); return v.length > 0 ? v[Math.floor(Math.random() * v.length)] : (exercisesDB.filter(ex => ex.grupo?.toLowerCase() === gReq.toLowerCase())[0] || null); };
  let str = focus === "fullbody" ? ["piernas", "pecho", "espalda", "hombros", "core"] : focus === "superior" ? ["pecho", "espalda", "hombros", "brazos", "core"] : ["piernas", "piernas", "piernas", "core"];
  str.forEach(g => { let ex = getRandomEx(g); if(ex && !currentWorkoutRoutine.find(e => e.id === ex.id)) { ex.loggedSets = []; ex.estimatedCals = Math.floor(Math.random() * 20) + 35; currentWorkoutRoutine.push(ex); } });
  const checkCool = document.getElementById('check-cooldown'); if(checkCool && checkCool.checked) { currentWorkoutRoutine.push({ id: 'cooldown', nombre: '❄️ Protocolo Recuperación', grupo: 'cardio', musculoPrincipal: 'Regeneración', equipamiento: ['corporal'], tips: '10 min estiramiento dinámico.', imagen: 'https://dummyimage.com/400x400/111827/00e5ff&text=ENFRIAR', loggedSets: [], isPhase: true }); }
  if(currentWorkoutRoutine.length === 0) { window.showToast('⚠️ Faltan datos.'); return; }
  localStorage.setItem('ironcore_saved_workout_routine', JSON.stringify(currentWorkoutRoutine));
  window.renderizarRutina(false); document.getElementById('workout-generator-card').style.display = 'none'; document.getElementById('workout-live-container').style.display = 'block'; document.getElementById('btn-start-workout').style.display = 'block'; document.getElementById('btn-finish-workout').style.display = 'none'; window.showToast('⚔️ Táctica lista.');
});

window.renderizarRutina = (isLiveMode) => {
  const container = document.getElementById('rutina-generada-lista'); if(!container) return; container.innerHTML = '';
  currentWorkoutRoutine.forEach((ex, idx) => {
    const displaySwap = (isLiveMode || ex.isPhase) ? 'none' : 'block'; const displayInputs = isLiveMode ? 'block' : 'none'; const imgSource = ex.imagen && ex.imagen.trim() !== "" ? ex.imagen : `https://dummyimage.com/400x400/111827/00e5ff&text=${encodeURIComponent(ex.nombre)}`; ex.loggedSets = ex.loggedSets || []; 
    let html = `<div class="plan-meal-card workout-card" data-index="${idx}"><div style="display:flex; justify-content:space-between; margin-bottom:10px;"><span style="font-size:15px; font-weight:900; color:#fff; text-transform:uppercase; letter-spacing:1px;">${ex.nombre}</span><button class="btn-swap" style="display:${displaySwap}; font-size:10px; padding:4px 10px; border-radius:6px; background:rgba(0,229,255,0.1); color:#00e5ff; border:1px solid #00e5ff; font-weight:800;" onclick="window.abrirMenuReemplazoEj(${idx})">🔄 Cambiar</button></div><div style="display:flex; gap:15px; align-items:center;"><img src="${imgSource}" onerror="this.onerror=null; this.src='https://dummyimage.com/400x400/111827/00e5ff';" style="width:75px; height:75px; border-radius:12px; object-fit:cover; border:2px solid rgba(0,229,255,0.3); box-shadow:0 4px 10px rgba(0,0,0,0.5);"><div style="flex:1;"><p style="font-size:11px; color:#00e5ff; margin:0 0 5px 0; font-weight:800; text-transform:uppercase; letter-spacing:1px;">🎯 ${ex.musculoPrincipal || 'General'}</p><p style="font-size:12px; color:#9ca3af; margin:0; line-height:1.5;">💡 ${ex.tips || 'Forma estricta.'}</p></div></div>`;
    if (isLiveMode) {
      let seriesHTML = ex.loggedSets.map((s, i) => `<li style="margin-bottom:8px; padding-bottom:8px; border-bottom:1px solid rgba(255,255,255,0.05); font-size:13px; color:#fff; display:flex; justify-content:space-between;"><span>Serie ${i+1}</span><span style="color:#00e5ff; font-weight:900;">${s.reps} ${!ex.isPhase ? `reps x ${s.peso} kg` : `min`}</span></li>`).join('');
      html += `<div class="workout-inputs" style="display:${displayInputs}; background: rgba(0,0,0,0.5); padding: 15px; border-radius: 12px; margin-top:15px; border:1px solid rgba(255,255,255,0.05);"><div style="display:flex; gap:10px; margin-bottom:15px;"><div style="flex:1;"><label style="font-size:10px; color:#9ca3af; font-weight:800;">${ex.isPhase?'MIN':'REPES'}</label><input type="number" id="reps-${idx}" class="neon-input" placeholder="10"></div>${!ex.isPhase ? `<div style="flex:1;"><label style="font-size:10px; color:#9ca3af; font-weight:800;">PESO (kg)</label><input type="number" id="peso-${idx}" class="neon-input" placeholder="50"></div>` : ''}<div style="flex:1;"><label style="font-size:10px; color:#9ca3af; font-weight:800;">DESC (s)</label><input type="number" id="descanso-${idx}" class="neon-input" value="90"></div></div><button class="btn btn-primary" style="width:100%; margin-top:0;" onclick="window.registrarSerieIndividual(${idx})">✅ Registrar ${ex.isPhase?'Fase':'Serie'}</button><ul id="lista-series-${idx}" style="list-style:none; padding:0; margin:15px 0 0 0;">${seriesHTML}</ul><div id="timer-container-${idx}" style="display:none; text-align:center; background:#1a2130; padding:15px; border-radius:12px; border: 1px dashed #ffaa00; margin-top:15px;"><span style="font-size:32px; font-weight:900; color:#ffaa00; display:block; margin-bottom:10px; text-shadow:0 0 10px rgba(255,170,0,0.5);">⏱️ <span id="time-left-${idx}">0</span>s</span><button class="btn btn-danger" style="margin-top:0; width:100%; font-size:12px;" onclick="window.terminarDescanso(${idx})">⏹️ Saltar Descanso</button></div></div>`;
    }
    html += `</div>`; container.innerHTML += html;
  });
};

window.abrirMenuReemplazoEj = idx => { window.workoutSwapTargetIndex = idx; const currentEx = currentWorkoutRoutine[idx]; const alternativas = exercisesDB.filter(e => e.grupo === currentEx.grupo && e.id !== currentEx.id); const listContainer = document.getElementById('sheet-swap-ex-list'); if(!listContainer) return; listContainer.innerHTML = ''; if(alternativas.length === 0) { listContainer.innerHTML = `<p style="font-size:12px; color:#ff3366;">Única táctica disponible para el filtro.</p>`; } else { alternativas.forEach(alt => { let objData = encodeURIComponent(JSON.stringify(alt)); listContainer.innerHTML += `<div class="swap-option-card" onclick="window.confirmarReemplazoEj('${objData}')" style="background:rgba(0,0,0,0.4); padding:15px; border-radius:10px; cursor:pointer; margin-bottom:10px; border:1px solid rgba(255,255,255,0.05); transition:0.2s;"><span style="font-size:10px; color:#00e5ff; font-weight:800; text-transform:uppercase; letter-spacing:1px;">${alt.musculoPrincipal}</span><b style="display:block; color:#fff; margin-top:5px; font-size:14px;">${alt.nombre}</b></div>`; }); } window.openSheet('sheet-swap-exercise'); };
window.confirmarReemplazoEj = encodedData => { if(window.workoutSwapTargetIndex > -1) { const newEx = JSON.parse(decodeURIComponent(encodedData)); newEx.loggedSets = []; newEx.estimatedCals = Math.floor(Math.random() * 20) + 35; currentWorkoutRoutine[window.workoutSwapTargetIndex] = newEx; localStorage.setItem('ironcore_saved_workout_routine', JSON.stringify(currentWorkoutRoutine)); window.renderizarRutina(false); window.closeSheet(); window.showToast(`✅ Movimiento ajustado.`); } };

window.registrarSerieIndividual = idx => { const repsInput = document.getElementById(`reps-${idx}`); const pesoInput = document.getElementById(`peso-${idx}`); const descansoInput = document.getElementById(`descanso-${idx}`); const ex = currentWorkoutRoutine[idx]; const reps = repsInput ? parseInt(repsInput.value) : 0; const peso = pesoInput ? (parseFloat(pesoInput.value) || 0) : 0; const descanso = descansoInput ? parseInt(descansoInput.value) || 90 : 90; if(!reps || reps <= 0) { window.showToast(`⚠️ Requiere número válido.`); return; } if(!ex.loggedSets) ex.loggedSets = []; ex.loggedSets.push({ reps, peso }); const lista = document.getElementById(`lista-series-${idx}`); lista.innerHTML += `<li style="margin-bottom:8px; padding-bottom:8px; border-bottom:1px solid rgba(255,255,255,0.05); font-size:13px; color:#fff; display:flex; justify-content:space-between;"><span>Serie ${ex.loggedSets.length}</span><span style="color:#00e5ff; font-weight:900;">${reps} ${ex.isPhase?'min':`reps x ${peso} kg`}</span></li>`; if(repsInput) repsInput.value = ''; window.iniciarDescanso(idx, descanso); };
window.iniciarDescanso = (idx, segundos) => { if(activeTimers[idx]) clearInterval(activeTimers[idx].interval); const container = document.getElementById(`timer-container-${idx}`); const textSpan = document.getElementById(`time-left-${idx}`); container.style.display = 'block'; let timeLeft = segundos; textSpan.innerText = timeLeft; activeTimers[idx] = { interval: setInterval(() => { timeLeft--; if(timeLeft <= 0) { window.terminarDescanso(idx); window.showToast('🔥 ¡AL HIERRO!'); } else { textSpan.innerText = timeLeft; } }, 1000) }; };
window.terminarDescanso = idx => { if(activeTimers[idx]) { clearInterval(activeTimers[idx].interval); delete activeTimers[idx]; } document.getElementById(`timer-container-${idx}`)?.style.setProperty('display', 'none'); };

document.getElementById('btn-start-workout')?.addEventListener('click', () => { window.renderizarRutina(true); document.getElementById('btn-start-workout').style.display = 'none'; document.getElementById('btn-finish-workout').style.display = 'block'; window.showToast('🔥 Foco Absoluto Activado.'); });
document.getElementById('btn-cancel-workout')?.addEventListener('click', () => { for (let idx in activeTimers) clearInterval(activeTimers[idx].interval); activeTimers = {}; document.getElementById('workout-live-container').style.display = 'none'; document.getElementById('workout-generator-card').style.display = 'block'; currentWorkoutRoutine = []; localStorage.removeItem('ironcore_saved_workout_routine'); window.showToast('❌ Misión Abortada.'); });
document.getElementById('btn-finish-workout')?.addEventListener('click', async function() { if (this.disabled) return; this.disabled = true; let validExercises = 0; let sessionCals = 0; for(let i = 0; i < currentWorkoutRoutine.length; i++) { const ex = currentWorkoutRoutine[i]; if(ex.loggedSets && ex.loggedSets.length > 0) { const totalSets = ex.loggedSets.length; const detalles = ex.loggedSets.map((s, idx) => `S${idx+1}: ${s.reps}${ex.isPhase?'min':`x${s.peso}kg`}`).join(' | '); const weightHighestOrLast = ex.loggedSets[ex.loggedSets.length - 1].peso; let exCals = 0; if(ex.isPhase) { let totalMins = 0; ex.loggedSets.forEach(s => totalMins += s.reps); exCals = totalMins * 10; } else { ex.loggedSets.forEach(s => { exCals += 15 + (s.peso * s.reps * 0.03); }); } exCals = Math.round(exCals); sessionCals += exCals; await window.registrarEntrenoNube(ex.nombre, `${totalSets} series (${detalles})`, weightHighestOrLast, "N/A", exCals); validExercises++; } } for (let idx in activeTimers) clearInterval(activeTimers[idx].interval); activeTimers = {}; if(validExercises > 0) { window.showToast(`✅ Victoria Asegurada. 🔥 ~${Math.round(sessionCals)} kcal.`); } else { window.showToast('⚠️ Sin series archivadas.'); } document.getElementById('workout-live-container').style.display = 'none'; document.getElementById('workout-generator-card').style.display = 'block'; document.getElementById('btn-start-workout').style.display = 'block'; document.getElementById('btn-finish-workout').style.display = 'none'; currentWorkoutRoutine = []; localStorage.removeItem('ironcore_saved_workout_routine'); this.disabled = false; });

window.abrirBuscadorCardio = () => {
  const container = document.getElementById('sheet-workout-dynamic'); if(!container) return;
  container.innerHTML = `<div style="padding: 10px;"><h3 style="color:#00e5ff; font-weight:900; text-transform:uppercase; margin-bottom:15px; text-align:center;">Cardio y Trote</h3><div style="background:rgba(0,0,0,0.5); padding:20px; border-radius:16px; border:1px solid rgba(255,255,255,0.05);"><label style="font-size:10px; color:#9ca3af; font-weight:800;">TIPO DE CARDIO</label><select id="cardio-type" class="neon-input"><option value="Trote en Cinta">Trote en Cinta</option><option value="Caminata Ligera">Caminata Ligera</option><option value="Bicicleta Estática">Bicicleta Estática</option><option value="Elíptica">Elíptica</option><option value="Saltar la Cuerda">Saltar la Cuerda</option></select><label style="font-size:10px; color:#9ca3af; font-weight:800; margin-top:15px;">TIEMPO EN MINUTOS</label><input type="number" id="cardio-mins" class="neon-input" placeholder="Ej: 30"><button class="btn btn-primary" style="width:100%; margin-top:20px; background:linear-gradient(90deg, #ffaa00, #ff5500); box-shadow:0 4px 15px rgba(255,170,0,0.4);" onclick="window.guardarCardioManual()">💾 ARCHIVAR CARDIO</button></div></div>`;
  window.openSheet('sheet-workout');
};

window.guardarCardioManual = async () => {
  const type = document.getElementById('cardio-type').value; const mInp = document.getElementById('cardio-mins'); const mins = mInp ? parseInt(mInp.value) : 0;
  if(!mins) return window.showToast('⚠️ Ingresa los minutos reales.');
  const factor = type.includes('Caminata') ? 6 : type.includes('Bicicleta') ? 8 : 11; 
  const cals = mins * factor;
  await window.registrarEntrenoNube(type.toUpperCase(), `${mins} minutos`, 0, "N/A", cals);
  window.closeSheet(); window.showToast(`✅ Cardio Guardado. 🔥 ~${cals} kcal.`);
};

window.abrirBuscadorManual = () => {
  const container = document.getElementById('sheet-workout-dynamic'); if(!container) return;
  container.innerHTML = `<div style="padding: 10px;"><h3 style="color:#00e5ff; font-weight:900; text-transform:uppercase; margin-bottom:15px; text-align:center;">Operación Táctica Manual</h3><div style="position:relative;"><input type="text" id="search-manual-ex" class="neon-input" placeholder="🔍 Escribe movimiento..." autocomplete="off"><div id="search-manual-results" class="search-results-box" style="position:absolute; width:100%;"></div></div><div id="manual-live-ui" style="display:none; margin-top:20px;"><div style="background:rgba(0,0,0,0.5); padding:20px; border-radius:16px; border:1px solid rgba(255,255,255,0.05); box-shadow:0 5px 20px rgba(0,0,0,0.5);"><h4 id="manual-selected-name" style="color:#fff; font-weight:900; margin-bottom:15px; text-transform:uppercase; font-size:15px;">Movimiento</h4><div style="display:flex; gap:10px; margin-bottom:15px;"><div style="flex:1;"><label style="font-size:10px; color:#9ca3af; font-weight:800;">REPES</label><input type="number" id="manual-rep" class="neon-input" style="margin-top:2px;"></div><div style="flex:1;"><label style="font-size:10px; color:#9ca3af; font-weight:800;">PESO (kg)</label><input type="number" id="manual-peso" class="neon-input" style="margin-top:2px;"></div><div style="flex:1;"><label style="font-size:10px; color:#9ca3af; font-weight:800;">DESC (s)</label><input type="number" id="manual-descanso" class="neon-input" value="90" style="margin-top:2px;"></div></div><button class="btn btn-primary" id="btn-add-manual-set" style="width:100%; margin-top:0;">✅ Imprimir Serie</button><ul id="manual-sets-list" style="list-style:none; padding:0; margin:15px 0 0 0;"></ul><div id="manual-timer" style="display:none; text-align:center; background:#1a2130; padding:15px; border-radius:12px; border: 1px dashed #ffaa00; margin-top:15px;"><span style="font-size:32px; font-weight:900; color:#ffaa00; display:block; margin-bottom:5px; text-shadow:0 0 10px rgba(255,170,0,0.5);">⏱️ <span id="manual-time-left">0</span>s</span><button class="btn btn-danger" onclick="document.getElementById('manual-timer').style.display='none'; clearInterval(window.manualInterval);" style="width:100%; margin-top:0; font-size:12px;">⏹️ Saltar</button></div><button class="btn btn-primary" id="btn-save-manual-workout" style="margin-top:20px; width:100%; background:linear-gradient(90deg, #ffaa00, #ff5500); display:none; box-shadow:0 4px 15px rgba(255,170,0,0.4);">💾 ARCHIVAR EN BITÁCORA</button></div></div></div>`; 
  window.openSheet('sheet-workout');
  
  const searchInput = document.getElementById('search-manual-ex'); const resultsBox = document.getElementById('search-manual-results'); let selectedExercise = null; let manualSets = [];
  searchInput.addEventListener('input', function() { const queryVal = this.value.toLowerCase(); resultsBox.innerHTML = ''; if(queryVal.length < 2) { resultsBox.style.display = 'none'; return; } const matches = exercisesDB.filter(ex => ex.nombre.toLowerCase().includes(queryVal) || (ex.musculoPrincipal && ex.musculoPrincipal.toLowerCase().includes(queryVal))); if(matches.length > 0) { resultsBox.style.display = 'block'; matches.slice(0, 10).forEach(match => { const div = document.createElement('div'); div.className = 'search-item'; div.innerHTML = `<span>${match.nombre}</span> <span class="search-item-muscle" style="font-size:10px; color:#ffaa00; font-weight:800; text-transform:uppercase;">${match.musculoPrincipal || 'General'}</span>`; div.onclick = () => { selectedExercise = match; manualSets = []; searchInput.value = match.nombre; resultsBox.style.display = 'none'; document.getElementById('manual-live-ui').style.display = 'block'; document.getElementById('manual-selected-name').innerText = match.nombre; document.getElementById('manual-sets-list').innerHTML = ''; document.getElementById('btn-save-manual-workout').style.display = 'none'; }; resultsBox.appendChild(div); }); } else { resultsBox.style.display = 'none'; } });
  document.getElementById('btn-add-manual-set').addEventListener('click', () => { const rInp = document.getElementById('manual-rep'); const pInp = document.getElementById('manual-peso'); const r = rInp ? parseInt(rInp.value) : 0; const p = pInp ? parseFloat(pInp.value) || 0 : 0; if(!r) return; manualSets.push({reps: r, peso: p}); document.getElementById('manual-sets-list').innerHTML += `<li style="margin-bottom:8px; padding-bottom:8px; border-bottom:1px solid rgba(255,255,255,0.05); font-size:13px; color:#fff; display:flex; justify-content:space-between;"><span>Serie ${manualSets.length}</span><span style="color:#00e5ff; font-weight:900;">${r} reps x ${p} kg</span></li>`; if(rInp) rInp.value = ''; document.getElementById('btn-save-manual-workout').style.display = 'block'; const dInp = document.getElementById('manual-descanso'); const d = dInp ? parseInt(dInp.value) || 90 : 90; document.getElementById('manual-timer').style.display = 'block'; let timeLeft = d; document.getElementById('manual-time-left').innerText = timeLeft; if(window.manualInterval) clearInterval(window.manualInterval); window.manualInterval = setInterval(() => { timeLeft--; document.getElementById('manual-time-left').innerText = timeLeft; if(timeLeft <= 0) { clearInterval(window.manualInterval); document.getElementById('manual-timer').style.display='none'; window.showToast('⏰ ¡A la carga!'); } }, 1000); });
  document.getElementById('btn-save-manual-workout').addEventListener('click', async function() { if(this.disabled) return; this.disabled = true; if(manualSets.length === 0) return; const detalles = manualSets.map((s, idx) => `S${idx+1}: ${s.reps}x${s.peso}kg`).join(' | '); const weightHighestOrLast = manualSets[manualSets.length - 1].peso; let cals = 0; manualSets.forEach(s => { cals += 15 + (s.peso * s.reps * 0.03); }); cals = Math.round(cals); await window.registrarEntrenoNube(selectedExercise.nombre, `${manualSets.length} series (${detalles})`, weightHighestOrLast, "N/A", cals); if(window.manualInterval) clearInterval(window.manualInterval); window.closeSheet(); window.showToast(`✅ Ejercicio Guardado.`); this.disabled = false; });
};
document.getElementById('btn-registrar-serie')?.addEventListener('click', window.abrirBuscadorManual);

// 9. HISTORIAL, CHECKINS Y REGISTROS
window.eliminarComidaNube = async (docId, cal, prot, carb, gras, nombre, btnElement) => { if(!confirm("¿Eliminar del historial?")) return; totalCalorias = Math.max(0, totalCalorias - cal); totalProt = Math.max(0, totalProt - prot); totalCarb = Math.max(0, totalCarb - carb); totalGrasa = Math.max(0, totalGrasa - gras); btnElement.closest('li')?.remove(); window.actualizarDashboard(); window.guardarEstadoNube(); if(window.currentUser && window.db && docId) { await window.deleteDoc(window.doc(window.db, "users", window.currentUser.uid, "days", window.getTodayKey(), "meals", docId)); const q = window.query(window.collection(window.db, "users", window.currentUser.uid, "history"), window.where("date", "==", window.getTodayKey()), window.where("nombre", "==", nombre), window.where("tipo", "==", "comida")); const snaps = await window.getDocs(q); snaps.forEach(async (d) => await window.deleteDoc(d.ref)); window.cargarHistorialYCheckins(window.currentUser.uid); } };
window.eliminarEntrenoNube = async (docId, cals, nombre, btnElement) => { if(!confirm("¿Eliminar del historial?")) return; totalQuemadas = Math.max(0, totalQuemadas - cals); btnElement.closest('li')?.remove(); window.actualizarDashboard(); window.guardarEstadoNube(); if(window.currentUser && window.db && docId) { await window.deleteDoc(window.doc(window.db, "users", window.currentUser.uid, "days", window.getTodayKey(), "workouts", docId)); const q = window.query(window.collection(window.db, "users", window.currentUser.uid, "history"), window.where("date", "==", window.getTodayKey()), window.where("nombre", "==", nombre.toUpperCase()), window.where("tipo", "==", "entreno")); const snaps = await window.getDocs(q); snaps.forEach(async (d) => await window.deleteDoc(d.ref)); window.cargarHistorialYCheckins(window.currentUser.uid); } };

window.registrarComidaNube = async (cal, prot, carb, gras, nombreDisplay) => { totalCalorias += cal; totalProt += prot; totalCarb += carb; totalGrasa += gras; await window.guardarEstadoNube(); window.actualizarDashboard(); let docId = null; if(window.currentUser && window.db) { const d = await window.addDoc(window.collection(window.db, "users", window.currentUser.uid, "days", window.getTodayKey(), "meals"), { nombre: nombreDisplay, cal, prot, carb, gras, timestamp: Date.now() }); docId = d.id; await window.addDoc(window.collection(window.db, "users", window.currentUser.uid, "history"), { tipo: 'comida', nombre: nombreDisplay, detalle: `🔥 ${cal} kcal | P:${prot}g C:${carb}g G:${gras}g`, date: window.getTodayKey(), timestamp: Date.now() }); } window.renderizarComidaEnUI(nombreDisplay, cal, prot, carb, gras, docId); document.querySelector('[data-target="page-dashboard"]')?.click(); if(window.currentUser) window.cargarHistorialYCheckins(window.currentUser.uid); };
window.registrarEntrenoNube = async (nombre, sets, weight, rpe, cals = 0) => { totalQuemadas += cals; await window.guardarEstadoNube(); window.actualizarDashboard(); let docId = null; if(window.currentUser && window.db) { const d = await window.addDoc(window.collection(window.db, "users", window.currentUser.uid, "days", window.getTodayKey(), "workouts"), { nombre, sets, weight, rpe, cals, timestamp: Date.now() }); docId = d.id; await window.addDoc(window.collection(window.db, "users", window.currentUser.uid, "history"), { tipo: 'entreno', nombre: nombre.toUpperCase(), detalle: `${sets} | 🔥 ${cals} kcal`, date: window.getTodayKey(), timestamp: Date.now() }); } window.renderizarEntrenoEnUI(nombre, sets, weight, rpe, cals, docId); if(window.currentUser) window.cargarHistorialYCheckins(window.currentUser.uid); };

window.renderizarComidaEnUI = (nombre, cal, prot, carb, gras, docId = null) => { const l = document.getElementById('lista-comidas'); if(!l) return; const li = document.createElement('li'); if(docId) li.setAttribute('data-id', docId); li.innerHTML = `<span style="color:#fff; font-weight:800; font-size:14px;">${nombre}</span><button class="btn-delete-item" style="background:none; border:none; color:var(--danger); font-size:14px; cursor:pointer; float:right;" onclick="window.eliminarComidaNube('${docId}', ${cal}, ${prot}, ${carb}, ${gras}, '${nombre.replace(/'/g, "\\'")}', this)">🗑️</button><br><span style="color: #9ca3af; font-size: 11px; margin-top:5px; display:block;">🔥 ${cal} kcal &nbsp;|&nbsp; <span style="color:#ff3366;">P: ${prot}g</span> &nbsp;|&nbsp; <span style="color:#00e5ff;">C: ${carb}g</span> &nbsp;|&nbsp; <span style="color:#ffaa00;">G: ${gras}g</span></span>`; l.appendChild(li); };
window.renderizarEntrenoEnUI = (nombre, sets, weight, rpe, cals = 0, docId = null) => { const l = document.getElementById('lista-entrenos'); if(!l) return; const li = document.createElement('li'); if(docId) li.setAttribute('data-id', docId); li.innerHTML = `<span style="color:#fff; font-weight:800; font-size:14px;">${nombre.toUpperCase()}</span><button class="btn-delete-item" style="background:none; border:none; color:var(--danger); font-size:14px; cursor:pointer; float:right;" onclick="window.eliminarEntrenoNube('${docId}', ${cals}, '${nombre.replace(/'/g, "\\'")}', this)">🗑️</button><br><span style="color: #9ca3af; font-size: 11px; margin-top:5px; display:flex; gap:10px; align-items:center;"><span>🏋️ ${sets}</span>${weight>0?`<span>Peso Máx: ${weight} kg</span>`:''} <span style="color:#ffaa00; font-weight:800; background:rgba(255,170,0,0.1); padding:2px 6px; border-radius:4px;">🔥 ~${cals} kcal</span></span>`; l.appendChild(li); };

window.cargarRegistrosDelDia = async (uid) => { const hoyKey = window.getTodayKey(); const listaComidas = document.getElementById('lista-comidas'); if(listaComidas) { listaComidas.innerHTML = ''; const snapshot = await window.getDocs(window.collection(window.db, "users", uid, "days", hoyKey, "meals")); snapshot.forEach(docSnap => { const i = docSnap.data(); window.renderizarComidaEnUI(i.nombre, i.cal, i.prot, i.carb, i.gras, docSnap.id); }); } const listaEntrenos = document.getElementById('lista-entrenos'); if(listaEntrenos) { listaEntrenos.innerHTML = ''; const snapshot = await window.getDocs(window.collection(window.db, "users", uid, "days", hoyKey, "workouts")); snapshot.forEach(docSnap => { const i = docSnap.data(); window.renderizarEntrenoEnUI(i.nombre, i.sets, i.weight, i.rpe, i.cals || 0, docSnap.id); }); } };

window.cargarHistorialYCheckins = async (uid) => {
  const histContainer = document.getElementById('historial-container'); const chkContainer = document.getElementById('checkin-history-container'); const hoyKey = window.getTodayKey();
  if(chkContainer && window.db) { chkContainer.innerHTML = '<p style="text-align:center; font-size:12px; color:#9ca3af;">Cargando check-ins...</p>'; const q = window.query(window.collection(window.db, "users", uid, "checkins"), window.orderBy("timestamp", "desc"), window.limit(15)); const snaps = await window.getDocs(q); let html = ''; let historialPesos = []; snaps.forEach(d => { let data = d.data(); historialPesos.push(data); html += `<div style="background:#111827; padding:12px; margin-bottom:10px; border-radius:8px; border-left:3px solid #ffaa00; display:flex; justify-content:space-between; align-items:center;"><span style="color:#00e5ff; font-weight:800; font-size:12px;">📅 ${data.fecha}</span><span style="color:#fff; font-weight:900; font-size:14px;">⚖️ ${data.peso} kg</span></div>`; }); chkContainer.innerHTML = html || '<p style="text-align:center; font-size:12px; color:#9ca3af;">No hay check-ins registrados.</p>'; if(historialPesos.length > 0) window.dibujarGraficoPerfil(historialPesos); }
  if(histContainer && window.db) {
    histContainer.innerHTML = '<p style="text-align:center; font-size:12px; color:#9ca3af;">Sincronizando jornada táctica...</p>';
    try {
      const mealsSnap = await window.getDocs(window.collection(window.db, "users", uid, "days", hoyKey, "meals")); const workoutsSnap = await window.getDocs(window.collection(window.db, "users", uid, "days", hoyKey, "workouts")); let itemsHoy = [];
      mealsSnap.forEach(m => { let data = m.data(); itemsHoy.push({ tipo: 'comida', nombre: data.nombre, detalle: `🔥 ${data.cal} kcal | P:${data.prot}g C:${data.carb}g G:${data.gras}g` }); });
      workoutsSnap.forEach(w => { let data = w.data(); itemsHoy.push({ tipo: 'entreno', nombre: data.nombre.toUpperCase(), detalle: `${data.sets} | 🔥 ${data.cals || 0} kcal` }); });
      let htmlJornada = `<div class="history-day"><div class="history-day-header" style="cursor:default;"><span>📅 Jornada Actual: ${hoyKey}</span> <span style="color:var(--primary); font-size:11px;">Sincronizado 🟢</span></div><div class="history-day-content" style="display:block; background:rgba(0,0,0,0.2); padding:15px;">`;
      if(itemsHoy.length === 0) { htmlJornada += `<p style="font-size:12px; color:#9ca3af; text-align:center; margin:0;">Sin registros hoy.</p>`; } else { itemsHoy.forEach(i => { htmlJornada += `<div style="margin-top:10px; padding-bottom:10px; border-bottom:1px solid rgba(255,255,255,0.05);"><b style="color:${i.tipo === 'entreno' ? '#00e5ff' : '#ff3366'}; font-size:13px;">${i.tipo === 'entreno' ? '🏋️' : '🍏'} ${i.nombre}</b><br><span style="font-size:11px; color:#9ca3af; display:block; margin-top:4px;">${i.detalle}</span></div>`; }); }
      htmlJornada += `</div></div>`;
      const qOld = window.query(window.collection(window.db, "users", uid, "history"), window.orderBy("timestamp", "desc"), window.limit(30)); const snapsOld = await window.getDocs(qOld); let agrupadoOld = {};
      snapsOld.forEach(d => { let data = d.data(); if(data.date !== hoyKey) { if(!agrupadoOld[data.date]) agrupadoOld[data.date] = []; agrupadoOld[data.date].push(data); } }); let htmlOld = '';
      for(const [fecha, items] of Object.entries(agrupadoOld)) { let itemsHtml = items.map(i => `<div style="margin-top:10px; padding-bottom:10px; border-bottom:1px solid rgba(255,255,255,0.05);"><b style="color:${i.tipo === 'entreno' ? '#00e5ff' : '#ff3366'}; font-size:13px;">${i.tipo === 'entreno' ? '🏋️' : '🍏'} ${i.nombre}</b><br><span style="font-size:11px; color:#9ca3af; display:block; margin-top:4px;">${i.detalle}</span></div>`).join(''); htmlOld += `<div class="history-day"><div class="history-day-header" onclick="const content = this.nextElementSibling; content.style.display = content.style.display === 'block' ? 'none' : 'block';"><span>📅 Jornada: ${fecha}</span> <span style="color:#fff;">▼</span></div><div class="history-day-content">${itemsHtml}</div></div>`; }
      histContainer.innerHTML = htmlJornada + htmlOld;
    } catch(e) { histContainer.innerHTML = '<p style="font-size:12px; color:#ff3366;">Error al sincronizar.</p>'; }
  }
};

window.borrarHistorialJornadas = async () => { if(!confirm("¿Borrar TODO el historial de jornadas?")) return; const q = window.query(window.collection(window.db, "users", window.currentUser.uid, "history")); const snaps = await window.getDocs(q); snaps.forEach(async (d) => await window.deleteDoc(d.ref)); window.showToast('🧹 Historial borrado.'); window.cargarHistorialYCheckins(window.currentUser.uid); };
window.borrarHistorialCheckins = async () => { if(!confirm("¿Borrar TODOS los check-ins de peso?")) return; const q = window.query(window.collection(window.db, "users", window.currentUser.uid, "checkins")); const snaps = await window.getDocs(q); snaps.forEach(async (d) => await window.deleteDoc(d.ref)); window.showToast('🧹 Check-ins borrados.'); window.cargarHistorialYCheckins(window.currentUser.uid); };

// CHECKIN DE PESO
document.getElementById('btn-confirm-checkin')?.addEventListener('click', async function() { 
  if (this.disabled) return; this.disabled = true; 
  const pesoInp = document.getElementById('checkin-peso'); const pesoVal = pesoInp ? parseFloat(pesoInp.value) : 0; 
  if(!pesoVal) { window.showToast('⚠️ Ingresa un peso válido.'); this.disabled = false; return; } 
  if(window.currentUser && window.db) { 
    await window.addDoc(window.collection(window.db, "users", window.currentUser.uid, "checkins"), { peso: pesoVal, fecha: window.getTodayKey(), timestamp: Date.now() }); 
    userProfile.peso = pesoVal; await window.guardarEstadoNube(); window.actualizarUIPerfil(); window.cargarHistorialYCheckins(window.currentUser.uid); 
  } 
  window.closeSheet(); if(pesoInp) pesoInp.value = ''; window.showToast('📈 Check-in guardado.'); this.disabled = false; 
});

// 10. ORÁCULO CLÍNICO Y BÁSES DE DATOS
let oracleDB = []; let exercisesDB = []; let weeklyPlan = []; let selectedDayIndex = 0; let activeAllergies = []; let dynamicDays = [];
async function inicializarBases() { try { const resFood = await fetch('alimentos.json?v=' + Date.now()); if (resFood.ok) oracleDB = await resFood.json(); } catch (e) {} try { const resEx = await fetch('ejercicios.json?v=' + Date.now()); if (!resEx.ok) throw new Error(); exercisesDB = await resEx.json(); } catch (e) {} }
inicializarBases();

const allergyInput = document.getElementById('oracle-allergies-input'); const allergyContainer = document.getElementById('allergy-tags-container');
if(allergyInput) { allergyInput.addEventListener('keypress', (e) => { if(e.key === 'Enter' || e.key === ',') { e.preventDefault(); const val = allergyInput.value.trim().toLowerCase(); if(val && !activeAllergies.includes(val)) { activeAllergies.push(val); window.renderAllergyChips(); } allergyInput.value = ''; } }); }
window.renderAllergyChips = () => { if(!allergyContainer) return; allergyContainer.innerHTML = ''; activeAllergies.forEach((allergy, index) => { const chip = document.createElement('div'); chip.className = 'allergy-chip'; chip.innerHTML = `<span>${allergy}</span><span class="allergy-chip-close" onclick="window.removeAllergy(${index})">×</span>`; allergyContainer.appendChild(chip); }); };
window.removeAllergy = index => { activeAllergies.splice(index, 1); window.renderAllergyChips(); };

window.calcularFechasSemana = () => { dynamicDays = []; const date = new Date(); const dayNames = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb']; const monthNames = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']; for(let i=0; i<7; i++) { let d = new Date(date); d.setDate(d.getDate() + i); dynamicDays.push({ index: i, shortName: dayNames[d.getDay()], fullName: `${dayNames[d.getDay()]}, ${d.getDate()} ${monthNames[d.getMonth()]}` }); } };

document.getElementById('btn-generar-plan')?.addEventListener('click', () => { if (oracleDB.length === 0) { window.showToast("⚠️ Sincronizando alimentos..."); return; } window.calcularFechasSemana(); window.generarPlanSemanal(); document.getElementById('oracle-form-card').style.display = 'none'; document.getElementById('plan-resultado').style.display = 'block'; window.showToast('🤖 Plan clínico generado.'); });

window.seleccionarDiaPlan = index => { selectedDayIndex = index; document.querySelectorAll('.day-chip').forEach(btn => btn.classList.remove('active')); document.querySelector(`.day-chip[data-day="${index}"]`)?.classList.add('active'); const ph = document.getElementById('plan-date-header'); if(ph) ph.innerText = dynamicDays[index].fullName; window.renderizarDiaSeleccionado(); };

window.generarPlanSemanal = () => { 
  weeklyPlan = []; const distribution = [ { tipo: 'desayuno', cals: metaCalorias * 0.30 }, { tipo: 'almuerzo', cals: metaCalorias * 0.40 }, { tipo: 'cena', cals: metaCalorias * 0.30 } ]; 
  for(let i=0; i<7; i++) { let dayMeals = distribution.map(slot => window.obtenerComidaAlgoritmo(slot.tipo, slot.cals, [])); weeklyPlan.push(dayMeals); } 
  window.guardarPlanNube(); window.renderizarSelectoresDias(); window.seleccionarDiaPlan(0); 
};

window.renderizarSelectoresDias = () => { const scrollContainer = document.getElementById('day-selector-container'); if(scrollContainer) { scrollContainer.innerHTML = ''; dynamicDays.forEach(day => { scrollContainer.innerHTML += `<button class="day-chip ${day.index === selectedDayIndex ? 'active' : ''}" data-day="${day.index}" onclick="window.seleccionarDiaPlan(${day.index})">${day.shortName}</button>`; }); } };
window.filtrarBaseDatos = (tipo, excludesId) => { let currentDietType = document.getElementById('oracle-diet-type')?.value || 'normal'; let isCeliac = document.getElementById('oracle-celiac')?.checked || false; let isLactose = document.getElementById('oracle-lactose')?.checked || false; let isSibo = document.getElementById('oracle-sibo')?.checked || false; let candidatos = oracleDB.filter(m => { if(m.tipo !== tipo) return false; if(m.dietas && !m.dietas.includes(currentDietType)) return false; if(excludesId && excludesId.includes(m.id)) return false; if(isCeliac && m.glutenFree === false) return false; if(isLactose && m.lactoseFree === false) return false; if(isSibo && m.siboSafe === false) return false; let jsonStr = JSON.stringify(m).toLowerCase(); for(let a of activeAllergies) { if(jsonStr.includes(a)) return false; } return true; }); if(candidatos.length === 0) candidatos = oracleDB.filter(m => m.tipo === tipo); return candidatos; };
window.calcularMacrosPorcion = (comidaBase, targetCals) => { const factor = targetCals / (comidaBase.calBase || 1); let ingredientesAdaptados = (comidaBase.ingredientes || []).map(ing => { let qtyCalculada = ing.baseQty * factor; qtyCalculada = ing.unidad === 'unidades' || ing.unidad === 'scoops' ? parseFloat(qtyCalculada.toFixed(1)) : Math.round(qtyCalculada); return { nombre: ing.nombre, cantidad: qtyCalculada, unidad: ing.unidad }; }); return { id: comidaBase.id, tipo: comidaBase.tipo, name: comidaBase.name, cals: Math.round(comidaBase.calBase * factor), prot: Math.round(comidaBase.prot * factor), carb: Math.round(comidaBase.carb * factor), gras: Math.round(comidaBase.gras * factor), ingredientes: ingredientesAdaptados }; };
window.obtenerComidaAlgoritmo = (tipo, targetCals, excludesId) => { const candidatos = window.filtrarBaseDatos(tipo, excludesId); if(candidatos.length === 0) return { id: 0, tipo: tipo, name: "Sin Opciones", cals: targetCals, prot: 0, carb: 0, gras: 0, ingredientes: [] }; const selected = candidatos[Math.floor(Math.random() * candidatos.length)]; return window.calcularMacrosPorcion(selected, targetCals); };

window.renderizarDiaSeleccionado = () => { 
  const container = document.getElementById('comidas-plan'); if(!container) return; container.innerHTML = ''; const dayMeals = weeklyPlan[selectedDayIndex] || []; 
  dayMeals.forEach((meal, idx) => { let ingredientesHTML = meal.ingredientes.length > 0 ? meal.ingredientes.map(i => `<span style="display:block; margin-bottom:3px; color:#e5e7eb; font-size:12px;">• ${i.cantidad} ${i.unidad} de ${i.nombre}</span>`).join('') : `• Sin ingredientes`; container.innerHTML += `<div class="plan-meal-card"><div class="plan-meal-header"><span class="plan-meal-title">${meal.tipo}</span><button class="btn-swap" onclick="window.abrirMenuReemplazo(${idx})">🔄 Cambiar</button></div><div class="plan-meal-desc"><b style="color:#00e5ff; font-size:14px; display:block; margin-bottom:8px;">${meal.name}</b>${ingredientesHTML}</div><div style="display:flex; justify-content:space-between; align-items:center; margin-top:15px; border-top:1px dashed rgba(255,255,255,0.1); padding-top:10px;"><span class="plan-meal-cals" style="background:transparent; border:none; padding:0;">🔥 ${meal.cals} kcal</span><span style="font-size:11px; color:var(--text-muted); font-weight:800;">P:<span style="color:#ff3366;">${meal.prot}g</span> C:<span style="color:#00e5ff;">${meal.carb}g</span> G:<span style="color:#ffaa00;">${meal.gras}g</span></span></div></div>`; }); 
};

let swapTargetIndex = -1;
window.abrirMenuReemplazo = mealIndex => { swapTargetIndex = mealIndex; const oldMeal = weeklyPlan[selectedDayIndex][mealIndex]; const targetCals = oldMeal.cals; let candidatos = window.filtrarBaseDatos(oldMeal.tipo, [oldMeal.id]); const listContainer = document.getElementById('sheet-swap-list'); if(!listContainer) return; listContainer.innerHTML = ''; if(candidatos.length === 0) { listContainer.innerHTML = `<p style="font-size:12px; color:#ff3366;">No hay opciones.</p>`; } else { for(let i=0; i<candidatos.length; i++) { let opcionEscalada = window.calcularMacrosPorcion(candidatos[i], targetCals); let objData = encodeURIComponent(JSON.stringify(opcionEscalada)); listContainer.innerHTML += `<div class="swap-option-card" onclick="window.confirmarReemplazo('${objData}')"><b style="display:block; color:#fff;">${opcionEscalada.name}</b><span style="font-size:11px; color:var(--primary);">🔥 ${opcionEscalada.cals} kcal | P: ${opcionEscalada.prot}g | C: ${opcionEscalada.carb}g | G: ${opcionEscalada.gras}g</span></div>`; } } window.openSheet('sheet-swap-meal'); };
window.confirmarReemplazo = encodedData => { if(swapTargetIndex > -1) { const newMeal = JSON.parse(decodeURIComponent(encodedData)); weeklyPlan[selectedDayIndex][swapTargetIndex] = newMeal; window.guardarPlanNube(); window.renderizarDiaSeleccionado(); window.closeSheet(); window.showToast(`✅ Actualizado.`); } };

window.guardarPlanNube = async () => { if(!weeklyPlan || weeklyPlan.length === 0) return; try { await window.setDoc(window.doc(window.db, "users", window.currentUser.uid, "weekly_plan", "current"), { plan: JSON.stringify(weeklyPlan), date: Date.now() }); localStorage.setItem('ironcore_saved_weekly_plan', JSON.stringify(weeklyPlan)); window.showToast("💾 Plan guardado."); } catch(e) {} };
window.recuperarPlanesGuardados = async () => { 
  if(!window.currentUser || !window.db) return; 
  try { 
    const planSnap = await window.getDoc(window.doc(window.db, "users", window.currentUser.uid, "weekly_plan", "current")); 
    if(planSnap.exists()) { 
      weeklyPlan = JSON.parse(planSnap.data().plan); localStorage.setItem('ironcore_saved_weekly_plan', JSON.stringify(weeklyPlan)); window.calcularFechasSemana(); document.getElementById('oracle-form-card').style.display = 'none'; document.getElementById('plan-resultado').style.display = 'block'; window.renderizarSelectoresDias(); window.seleccionarDiaPlan(0); 
    } 
  } catch(e) {} 
  const savedRoutine = localStorage.getItem('ironcore_saved_workout_routine'); 
  if(savedRoutine) { try { currentWorkoutRoutine = JSON.parse(savedRoutine); window.renderizarRutina(false); document.getElementById('workout-generator-card').style.display = 'none'; document.getElementById('workout-live-container').style.display = 'block'; document.getElementById('btn-start-workout').style.display = 'block'; document.getElementById('btn-finish-workout').style.display = 'none'; } catch(e) {} } 
};

window.generarListaCompras = () => { const ul = document.getElementById('lista-compras-ui'); if(!ul) return; let listaConsolidada = {}; weeklyPlan.forEach(dia => { dia.forEach(comida => { comida.ingredientes.forEach(ing => { let key = `${ing.nombre} (${ing.unidad})`; listaConsolidada[key] = (listaConsolidada[key] || 0) + ing.cantidad; }); }); }); ul.innerHTML = ''; for (let key in listaConsolidada) { let rawQty = listaConsolidada[key]; let qtyDisplay = key.includes('unidades') || key.includes('scoops') ? rawQty.toFixed(1) : Math.round(rawQty); let match = key.match(/(.*) \((.*)\)/); let nombreLimpio = match ? match[1] : key; let unidadLimpia = match ? match[2] : ''; ul.innerHTML += `<li><input type="checkbox" style="accent-color:var(--primary); width:18px; height:18px;"> <span style="flex:1;">${nombreLimpio}</span> <b style="color:var(--primary); font-size:12px; background:rgba(0,229,255,0.1); padding:4px 8px; border-radius:6px;">${qtyDisplay} ${unidadLimpia}</b></li>`; } window.openSheet('sheet-compras'); };

document.getElementById('btn-add-planned')?.addEventListener('click', () => { if(!weeklyPlan || weeklyPlan.length === 0) { window.showToast('⚠️ Genera el oráculo semanal primero.'); return; } const listContainer = document.getElementById('sheet-planned-list'); if(!listContainer) return; listContainer.innerHTML = ''; const todaysPlan = weeklyPlan[0]; todaysPlan.forEach(meal => { let objData = encodeURIComponent(JSON.stringify(meal)); listContainer.innerHTML += `<div class="swap-option-card" onclick="window.registrarComidaPlaneada('${objData}')"><span style="font-size:10px; color:var(--primary); font-weight:800; text-transform:uppercase;">${meal.tipo}</span><b style="display:block; color:#fff; margin-top:4px;">${meal.name}</b><span>🔥 ${meal.cals} kcal | P: ${meal.prot}g | C: ${meal.carb}g | G: ${meal.gras}g</span></div>`; }); window.openSheet('sheet-planned-meals'); });
window.registrarComidaPlaneada = async encodedData => { try { const meal = JSON.parse(decodeURIComponent(encodedData)); let nombreFinal = `[${meal.tipo.charAt(0).toUpperCase() + meal.tipo.slice(1)}] ${meal.name}`; await window.registrarComidaNube(meal.cals, meal.prot, meal.carb, meal.gras, nombreFinal); window.closeSheet(); window.showToast(`✅ Menú registrado.`); } catch(e) { window.closeSheet(); } };

// LEADERBOARD
window.cargarLeaderboard = async () => { 
  const container = document.getElementById('leaderboard-list'); if(!container || !window.db) return; 
  container.innerHTML = `<p style="font-size: 12px; color: #9ca3af; text-align: center;">Cargando guerreros...</p>`; 
  try { 
    const q = window.query(window.collection(window.db, "leaderboard"), window.orderBy("multiplicador", "desc"), window.limit(20)); 
    const snapshot = await window.getDocs(q); 
    if(snapshot.empty) { container.innerHTML = `<p style="font-size: 12px; color: #9ca3af; text-align: center;">El dojo está vacío.</p>`; return; } 
    let html = "", pos = 1; 
    snapshot.forEach(docSnap => { 
      const d = docSnap.data(); const topClass = pos===1?"top-1":pos===2?"top-2":pos===3?"top-3":""; const medal = pos===1?"🥇":pos===2?"🥈":pos===3?"🥉":`#${pos}`; 
      html += `<div class="leaderboard-item ${topClass}"><div class="lb-rank-num">${medal}</div><div class="lb-user-info"><img class="lb-avatar" src="${window.generarAvatarPorRango(d.nombre, d.rango, 'bottts')}"><div><span class="lb-name">${d.nombre}</span><span class="lb-badge" style="color: ${d.colorRango};">${d.rango}</span></div></div><div class="lb-score"><span class="lb-multiplier">${d.multiplicador}x</span><span class="lb-kg">${d.totalKg} kg</span></div></div>`; pos++; 
    }); 
    container.innerHTML = html; 
  } catch(e) { container.innerHTML = `<p style="font-size: 12px; color: #ff3366; text-align: center;">Error al cargar.</p>`; } 
};
document.getElementById('btn-refresh-leaderboard')?.addEventListener('click', window.cargarLeaderboard);

if ('serviceWorker' in navigator) { window.addEventListener('load', () => { navigator.serviceWorker.register('sw.js').catch(console.log); }); }
