// ============================================================================
// --- IRONCORE ENGINE V2 (SINCRONIZACIÓN PERFECTA, CARDIO & SOCIAL FIX) ---
// ============================================================================

// 1. DECLARACIONES GLOBALES Y UTILIDADES (AQUÍ ARREGLAMOS EL ERROR DE INICIO)
let totalCalorias=0, totalProt=0, totalCarb=0, totalGrasa=0, totalAgua=0, totalQuemadas=0, userStreak=1;
let metaCalorias=2500, metaProt=165, metaCarb=275, metaGrasa=69;
let currentRankName="Ashigaru";
let userProfile={perfilCompleto:false, nickname:"", genero:"M", edad:25, peso:75, altura:175, metaObj:0, actividad:1.55, avatarStyle:"bottts"};

window.getTodayKey = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
window.showToast = msg => { const t = document.getElementById('toast-notif'); if(t){ t.innerHTML=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),3500); } };

window.guardarEstadoNube = async () => { if(!window.db || !window.currentUser) return; try { await window.setDoc(window.doc(window.db, "users", window.currentUser.uid), { calorias: totalCalorias, proteina: totalProt, carbos: totalCarb, grasa: totalGrasa, agua: totalAgua, quemadas: totalQuemadas, metaCal: metaCalorias, metaProt: metaProt, metaCarb: metaCarb, metaGrasa: metaGrasa, streak: userStreak, ultimaFecha: localStorage.getItem('ic_ultima_fecha'), currentRankName, ...userProfile }, { merge: true }); } catch(e) {} };

window.actualizarUIHeader = () => { const dn = document.getElementById('user-display-name'); if(dn) dn.innerText = userProfile.nickname.toUpperCase(); const wb = document.getElementById('user-welcome-box'); if(wb) wb.style.display = 'flex'; };

window.verificarCambioDeDia = () => { const hoy = new Date().toDateString(); const ult = localStorage.getItem('ic_ultima_fecha'); if (!ult) localStorage.setItem('ic_ultima_fecha', hoy); else if (ult !== hoy) { totalCalorias=0; totalProt=0; totalCarb=0; totalGrasa=0; totalAgua=0; totalQuemadas=0; userStreak++; localStorage.setItem('ic_ultima_fecha', hoy); window.guardarEstadoNube(); window.showToast('🌙 Nuevo día. ¡Racha incrementada!'); } const st = document.getElementById('header-streak'); if(st) st.innerText = `🔥 Racha: ${userStreak} días`; };

window.reiniciarDiaActual = () => { if(confirm("¿Reiniciar balance de hoy?")) { totalCalorias=0; totalProt=0; totalCarb=0; totalGrasa=0; totalAgua=0; totalQuemadas=0; window.guardarEstadoNube(); window.actualizarDashboard(); window.actualizarAguaUI(); const lc = document.getElementById('lista-comidas'); if(lc) lc.innerHTML = ''; window.showToast('🔄 Restablecido.'); } };

// 2. DASHBOARD Y UI
window.actualizarDashboard = () => { 
  const dashContainer = document.getElementById('page-dashboard'); if(!dashContainer) return;
  let dashUI = document.getElementById('iron-dash-ui-advanced');
  if(!dashUI) { document.querySelectorAll('.card-main, .macros, .water-card, .coach-tip, #btn-checkin, #calorias-total, .energy-breakdown, .chart-container').forEach(el => el.style.display = 'none'); dashUI = document.createElement('div'); dashUI.id = 'iron-dash-ui-advanced'; dashContainer.insertBefore(dashUI, dashContainer.firstChild); }
  const calNetas = Math.max(0, totalCalorias - totalQuemadas); const calPct = Math.min(100, (calNetas / metaCalorias) * 100) || 0;
  const prPct = Math.min(100, (totalProt/metaProt)*100) || 0; const cbPct = Math.min(100, (totalCarb/metaCarb)*100) || 0; const grPct = Math.min(100, (totalGrasa/metaGrasa)*100) || 0;
  const calColor = calNetas > metaCalorias ? '#ff3366' : '#00e5ff';
  let tmb = userProfile.genero === 'M' ? (10 * userProfile.peso) + (6.25 * userProfile.altura) - (5 * userProfile.edad) + 5 : (10 * userProfile.peso) + (6.25 * userProfile.altura) - (5 * userProfile.edad) - 161;

  dashUI.innerHTML = `
    <button class="btn btn-warning" style="width:100%; margin-bottom: 20px; font-size:13px; text-transform:uppercase;" onclick="window.openSheet('sheet-checkin')">📈 Registrar Peso de Hoy</button>
    <div class="card" style="padding:25px 20px; position:relative;">
      <div style="display:flex; justify-content:space-between; margin-bottom:25px;"><h3 style="margin:0; font-size:15px; color:#fff; text-transform:uppercase; letter-spacing:1px;">Flujo de Energía</h3><button class="btn-clear-history" style="font-size:10px; color:var(--primary); border:1px solid var(--primary); background:rgba(0,229,255,0.1);" onclick="window.reiniciarDiaActual()">🔄 Reiniciar</button></div>
      <div class="energy-ring" style="--pct: ${calPct}%; --primary: ${calColor};"><div class="energy-ring-content"><span style="font-size:40px; font-weight:900; color:${calColor}; text-shadow:0 0 15px rgba(0,229,255,0.5); display:block; line-height:1;">${calNetas}</span><span style="font-size:10px; color:#9ca3af; text-transform:uppercase; font-weight:800; letter-spacing:1px; display:block; margin-top:5px;">Kcal Netas</span></div></div>
      <div style="display:flex; justify-content:space-around; text-align:center; margin-bottom:20px; border-top:1px dashed rgba(255,255,255,0.1); padding-top:20px;"><div><span style="font-size:10px; color:#9ca3af; font-weight:800; display:block; margin-bottom:4px;">CONSUMO</span><b style="color:#00e5ff; font-size:16px;">+${totalCalorias}</b></div><div><span style="font-size:10px; color:#9ca3af; font-weight:800; display:block; margin-bottom:4px;">QUEMADO</span><b style="color:#ffaa00; font-size:16px;">🔥-${totalQuemadas}</b></div><div><span style="font-size:10px; color:#9ca3af; font-weight:800; display:block; margin-bottom:4px;">META DÍA</span><b style="color:#fff; font-size:16px;">${metaCalorias}</b></div></div>
      <div style="text-align:center; margin-bottom:20px; font-size:11px; color:#9ca3af; font-weight:bold;">Metabolismo Basal (TMB): <span style="color:#fff;">${Math.round(tmb)} kcal/día</span></div>
      <div class="stats-grid" style="margin-top:0;"><div class="stat-panel"><div class="stat-title">Proteína</div><div class="stat-value" style="font-size:18px;">${totalProt}<small style="font-size:10px; color:var(--text-muted);">/${metaProt}g</small></div><div class="macro-progress-container"><div class="macro-progress-fill" style="width:${prPct}%; background:#ff3366; box-shadow: 0 0 10px #ff3366;"></div></div></div><div class="stat-panel"><div class="stat-title">Carbos</div><div class="stat-value" style="font-size:18px;">${totalCarb}<small style="font-size:10px; color:var(--text-muted);">/${metaCarb}g</small></div><div class="macro-progress-container"><div class="macro-progress-fill" style="width:${cbPct}%; background:#00e5ff; box-shadow: 0 0 10px #00e5ff;"></div></div></div><div class="stat-panel stat-panel-full"><div class="stat-title">Grasas</div><div class="stat-value" style="font-size:18px;">${totalGrasa}<small style="font-size:10px; color:var(--text-muted);">/${metaGrasa}g</small></div><div class="macro-progress-container"><div class="macro-progress-fill" style="width:${grPct}%; background:#ffaa00; box-shadow: 0 0 10px #ffaa00;"></div></div></div></div>
    </div>
    <div class="card" style="padding:20px; margin-top:20px;"><div style="display:flex; justify-content:space-between; margin-bottom:15px;"><h3 style="margin:0; font-size:14px; color:#fff; text-transform:uppercase; letter-spacing:1px;">💧 Hidratación</h3><button style="background:rgba(0,229,255,0.1); border:1px solid #00e5ff; border-radius:6px; color:#00e5ff; font-size:11px; font-weight:bold; cursor:pointer; padding:4px 8px;" onclick="window.resetAgua()">Reset</button></div><div style="display:flex; align-items:center; gap:15px;"><div style="flex:1;"><div class="stat-value" style="font-size:20px; color:#00e5ff;">${totalAgua/1000}L <span style="font-size:10px; color:#9ca3af;">/ 3.0L</span></div><div class="macro-progress-container" style="height:12px;"><div class="macro-progress-fill" id="water-fill-bar" style="width:${Math.min(100, (totalAgua/3000)*100)}%; background:#00e5ff; box-shadow: 0 0 10px #00e5ff;"></div></div></div><button class="btn btn-primary" style="width:auto; margin:0; padding:15px; font-size:12px;" onclick="window.agregarAgua(500)">+ 500ml</button></div></div>
  `;
};

window.actualizarAguaUI = () => { const meta = 3000; let pct = Math.min(100, Math.round((totalAgua/meta)*100)); const wb = document.getElementById('water-fill-bar'); if(wb) wb.style.width = `${pct}%`; window.guardarEstadoNube(); };
window.agregarAgua = ml => { totalAgua += ml; window.actualizarAguaUI(); window.actualizarDashboard(); window.showToast(`💧 +${ml} ml añadidos.`); }; window.resetAgua = () => { totalAgua = 0; window.actualizarAguaUI(); window.actualizarDashboard(); window.showToast(`🔄 Hidratación reiniciada.`); };

// 3. FIREBASE INIT E IMPORTACIONES
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import { getAuth, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult, signOut, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js";
import { getFirestore, doc, setDoc, getDoc, collection, addDoc, getDocs, deleteDoc, query, orderBy, limit, where } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";

const app = initializeApp({ apiKey: "AIzaSyAK3QRT5FOqe9q-hxI3NWtTvZT2uGGLCTU", authDomain: "ironcoreapp-66a12.firebaseapp.com", projectId: "ironcoreapp-66a12", storageBucket: "ironcoreapp-66a12.firebasestorage.app", messagingSenderId: "673931910641", appId: "1:673931910641:web:eb3d5a830cbcd31fc6f850" });
window.auth = getAuth(app); window.db = getFirestore(app);
window.doc = doc; window.setDoc = setDoc; window.getDoc = getDoc; window.collection = collection; window.addDoc = addDoc; window.getDocs = getDocs; window.deleteDoc = deleteDoc; window.query = query; window.orderBy = orderBy; window.limit = limit; window.where = where;

// 4. CARGA DE DATOS PRINCIPAL
window.cargarDatosDesdeNube = async (uid) => {
  if(!window.db) return; const docSnap = await window.getDoc(window.doc(window.db, "users", uid)); 
  if (docSnap.exists()) { const d = docSnap.data(); totalCalorias = d.calorias || 0; totalProt = d.proteina || 0; totalCarb = d.carbos || 0; totalGrasa = d.grasa || 0; totalAgua = d.agua || 0; totalQuemadas = d.quemadas || 0; metaCalorias = d.metaCal || 2500; metaProt = d.metaProt || 165; metaCarb = d.metaCarb || 275; metaGrasa = d.metaGrasa || 69; userStreak = d.streak || 1; userProfile.perfilCompleto = d.perfilCompleto || false; userProfile.nickname = d.nickname || ""; userProfile.genero = d.genero || "M"; userProfile.edad = d.edad || 25; userProfile.peso = d.peso || 75; userProfile.altura = d.altura || 175; userProfile.metaObj = d.metaObj !== undefined ? d.metaObj : 0; userProfile.actividad = d.actividad || 1.55; currentRankName = d.currentRankName || "Ashigaru"; userProfile.avatarStyle = d.avatarStyle || "bottts"; if(!d.nickname_lower && userProfile.nickname) { userProfile.nickname_lower = userProfile.nickname.toLowerCase(); window.guardarEstadoNube(); } } 
  if(!userProfile.perfilCompleto) { window.abrirOnboarding(false); } else { window.actualizarUIHeader(); window.actualizarUIPerfil(); } 
  window.verificarCambioDeDia(); window.actualizarDashboard(); window.actualizarAguaUI(); await window.cargarRegistrosDelDia(uid); await window.cargarHistorialYCheckins(uid); window.recuperarPlanesGuardados();
};

onAuthStateChanged(window.auth, async (user) => {
  if (user) { window.currentUser = user; document.getElementById('auth-screen').style.display = 'none'; await window.cargarDatosDesdeNube(user.uid); window.iniciarNotificacionesEnVivo(user.uid); } 
  else { window.currentUser = null; document.getElementById('auth-screen').style.display = 'flex'; }
});
document.getElementById('btn-google-login')?.addEventListener('click', async () => { window.showToast('🔄 Conectando...'); const p = new GoogleAuthProvider(); p.setCustomParameters({ prompt: 'select_account' }); try { await signInWithPopup(window.auth, p); } catch(e) { await signInWithRedirect(window.auth, p); } });

// 5. NAVEGACIÓN Y BOTTOM SHEETS
document.querySelectorAll('.nav-item').forEach(btn => { btn.addEventListener('click', () => { document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active')); document.querySelectorAll('.page').forEach(p => { p.classList.remove('active'); p.style.display = 'none'; }); btn.classList.add('active'); const tgt = document.getElementById(btn.getAttribute('data-target')); if(tgt) { tgt.classList.add('active'); tgt.style.display = 'block'; } if(btn.getAttribute('data-target') === 'page-social') window.cargarModuloSocialCompleto(); }); });
document.querySelectorAll('.tab-btn-diet, .tab-btn-train').forEach(btn => { btn.addEventListener('click', () => { const group = btn.className.split(' ')[0]; document.querySelectorAll(`.${group}`).forEach(t => t.classList.remove('active')); document.querySelectorAll(`.${btn.getAttribute('data-tab').startsWith('tab-r')||btn.getAttribute('data-tab').startsWith('tab-p')?group.replace('btn','sub'):group.replace('btn','sub')}`).forEach(s => s.style.display = 'none'); btn.classList.add('active'); document.getElementById(btn.getAttribute('data-tab')).style.display = 'block'; if(btn.getAttribute('data-tab') === 'tab-leaderboard') window.cargarLeaderboard(); }); });

const overlay = document.getElementById('sheet-overlay');
window.openSheet = id => { const s = document.getElementById(id); if(overlay) overlay.style.display = 'block'; if(s) { s.classList.add('open'); setTimeout(() => s.style.bottom = '0', 10); window.currentActiveSheet = s; } };
window.closeSheet = () => { document.querySelectorAll('.bottom-sheet').forEach(s => { s.style.bottom = '-100%'; s.classList.remove('open'); }); if(overlay) overlay.style.display = 'none'; window.currentActiveSheet = null; };
if(overlay) overlay.addEventListener('click', window.closeSheet);

// 6. PERFIL Y GRÁFICO
window.actualizarUIPerfil = () => { 
  const profPage = document.getElementById('profile-dynamic-root'); if(!profPage) return;
  let labelMeta = userProfile.metaObj === -500 ? "Déficit Agresivo" : userProfile.metaObj === -300 ? "Definición" : userProfile.metaObj === 300 ? "Volumen" : "Mantenimiento";
  let avatarUrl = `https://api.dicebear.com/7.x/${userProfile.avatarStyle}/svg?seed=${userProfile.nickname}-${currentRankName}&backgroundColor=111827`;
  profPage.innerHTML = `
    <div class="card" style="text-align: center; position: relative;">
      <div style="position:relative; display:inline-block;"><img src="${avatarUrl}" style="width: 100px; height: 100px; border-radius: 50%; border: 3px solid var(--primary); margin-bottom: 10px; object-fit: cover; background: #1a2130; box-shadow: 0 0 20px rgba(0,229,255,0.4);"><button onclick="window.cambiarEstiloAvatar()" style="position:absolute; bottom:10px; right:-10px; background:var(--primary); color:#000; border:none; border-radius:50%; width:35px; height:35px; font-size:18px; cursor:pointer; box-shadow:0 2px 10px rgba(0,0,0,0.8); z-index:10; transition:0.2s;">🎲</button></div>
      <h2 style="margin: 0; color: #fff; font-size: 26px; text-transform: uppercase; font-weight:900; letter-spacing:1px;">${userProfile.nickname}</h2>
      <div style="color:var(--accent); font-size:13px; font-weight:900; margin-top:5px; text-transform:uppercase; letter-spacing:2px;">Rango: ${currentRankName}</div>
      <span style="display:inline-block; padding: 6px 12px; background: rgba(0,229,255,0.1); border: 1px solid rgba(0,229,255,0.3); color: var(--primary); font-size: 11px; font-weight:800; border-radius: 12px; margin-top: 15px; text-transform: uppercase;">Meta: ${labelMeta}</span>
      <div class="stats-grid" style="margin-top: 25px; text-align: left;"><div class="stat-panel"><div class="stat-title">Peso</div><div class="stat-value" style="font-size:18px;">${userProfile.peso} <small style="font-size:10px; color:var(--text-muted);">kg</small></div></div><div class="stat-panel"><div class="stat-title">Altura</div><div class="stat-value" style="font-size:18px;">${userProfile.altura} <small style="font-size:10px; color:var(--text-muted);">cm</small></div></div><div class="stat-panel"><div class="stat-title">Edad</div><div class="stat-value" style="font-size:18px;">${userProfile.edad} <small style="font-size:10px; color:var(--text-muted);">años</small></div></div><div class="stat-panel"><div class="stat-title">Género</div><div class="stat-value" style="font-size:18px;">${userProfile.genero === 'M' ? 'Hombre' : 'Mujer'}</div></div></div>
      <div style="display:flex; gap:10px; margin-top:25px;"><button class="btn btn-primary" style="flex:2;" onclick="window.abrirOnboarding(true)">⚙️ Modificar Parámetros</button><button class="btn btn-secondary" style="flex:1; border-color:#ff3366; color:#ff3366;" onclick="window.cerrarSesionApp()">Salir</button></div>
    </div><div id="wrapper-profile-chart-inj"></div>`;
};

let profileChartInstance = null;
window.dibujarGraficoPerfil = function(historialPesos) {
  const chartWrapper = document.getElementById('wrapper-profile-chart-inj'); if(!chartWrapper) return;
  chartWrapper.innerHTML = `<div class="card" style="padding: 20px;"><h4 style="font-size: 13px; color: var(--primary); text-transform: uppercase; font-weight: 900; letter-spacing: 1px; margin: 0 0 20px 0;">📈 Proyección vs Realidad</h4><div style="height: 250px; width: 100%;"><canvas id="profile-chart-canvas-inj"></canvas></div></div>`;
  const ctx = document.getElementById('profile-chart-canvas-inj'); if(!ctx) return;
  if(profileChartInstance) profileChartInstance.destroy();
  const labels = historialPesos.map(item => item.fecha.split('-').slice(1).join('/')).reverse(); const realData = historialPesos.map(item => item.peso).reverse();
  let projectionData = [];
  if(realData.length > 0) { let startWeight = realData[0]; let dailyChange = userProfile.metaObj === -500 ? -0.1 : userProfile.metaObj === -300 ? -0.04 : userProfile.metaObj === 300 ? 0.04 : 0; projectionData = labels.map((_, i) => parseFloat((startWeight + (dailyChange * i * 3)).toFixed(1))); }
  profileChartInstance = new Chart(ctx.getContext('2d'), { type: 'line', data: { labels: labels, datasets: [ { label: 'Peso Real', data: realData, borderColor: '#00e5ff', backgroundColor: 'rgba(0, 229, 255, 0.2)', borderWidth: 4, fill: true, tension: 0.4, pointBackgroundColor: '#fff', pointRadius: 5, pointBorderColor: '#00e5ff', pointBorderWidth: 2 }, { label: 'Ruta Ideal', data: projectionData, borderColor: 'rgba(255, 170, 0, 0.8)', borderDash: [6, 6], borderWidth: 2, fill: false, pointRadius: 0 } ] }, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { display: true, labels: { color: '#fff' } } }, scales: { y: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks:{color:'#9ca3af'} }, x: { grid: { display: false }, ticks:{color:'#9ca3af'} } } } });
};

// 7. INYECCIÓN BOTÓN CARDIO
document.addEventListener('DOMContentLoaded', () => {
  const btnManual = document.getElementById('btn-registrar-serie');
  if(btnManual && !document.getElementById('btn-registrar-cardio')) {
    const btnCardio = document.createElement('button'); btnCardio.id = 'btn-registrar-cardio'; btnCardio.className = 'btn btn-secondary'; btnCardio.style.cssText = 'width: 100%; margin-top: 10px; font-size:11px; border-color:#00e5ff; color:#00e5ff; box-shadow:0 0 10px rgba(0,229,255,0.2);'; btnCardio.innerText = '🏃‍♂️ Agregar Sesión de Cardio'; btnCardio.onclick = window.abrirBuscadorCardio;
    btnManual.parentNode.insertBefore(btnCardio, btnManual.nextSibling);
  }
});

window.abrirBuscadorCardio = () => {
  const container = document.getElementById('sheet-workout-dynamic'); if(!container) return;
  container.innerHTML = `<div style="padding: 10px;"><h3 style="color:#00e5ff; font-weight:900; text-transform:uppercase; margin-bottom:15px; text-align:center;">Cardio y Trote</h3><div style="background:rgba(0,0,0,0.5); padding:20px; border-radius:16px; border:1px solid rgba(255,255,255,0.05);"><label style="font-size:10px; color:#9ca3af; font-weight:800;">TIPO DE CARDIO</label><select id="cardio-type" class="neon-input"><option value="Trote en Cinta">Trote en Cinta</option><option value="Caminata Ligera">Caminata Ligera</option><option value="Bicicleta Estática">Bicicleta Estática</option><option value="Elíptica">Elíptica</option></select><label style="font-size:10px; color:#9ca3af; font-weight:800; margin-top:15px;">TIEMPO EN MINUTOS</label><input type="number" id="cardio-mins" class="neon-input" placeholder="Ej: 30"><button class="btn btn-primary" style="width:100%; margin-top:20px; background:linear-gradient(90deg, #ffaa00, #ff5500); box-shadow:0 4px 15px rgba(255,170,0,0.4);" onclick="window.guardarCardioManual()">💾 ARCHIVAR CARDIO</button></div></div>`;
  window.openSheet('sheet-workout');
};

window.guardarCardioManual = async () => {
  const type = document.getElementById('cardio-type').value; const mins = parseInt(document.getElementById('cardio-mins').value);
  if(!mins) return window.showToast('⚠️ Ingresa los minutos reales.');
  const factor = type.includes('Caminata') ? 6 : type.includes('Bicicleta') ? 8 : 11; // Kcal por minuto aprox
  const cals = mins * factor;
  await window.registrarEntrenoNube(type.toUpperCase(), `${mins} minutos`, 0, "N/A", cals);
  window.closeSheet(); window.showToast(`✅ Cardio Guardado. 🔥 ~${cals} kcal.`);
};

// 8. SINCRONIZACIÓN Y BORRADO DE BITÁCORAS
window.eliminarComidaNube = async (docId, cal, prot, carb, gras, nombre, btnElement) => { 
  if(!confirm("¿Eliminar del historial?")) return; 
  totalCalorias = Math.max(0, totalCalorias - cal); totalProt = Math.max(0, totalProt - prot); totalCarb = Math.max(0, totalCarb - carb); totalGrasa = Math.max(0, totalGrasa - gras); btnElement.closest('li')?.remove(); window.actualizarDashboard(); window.guardarEstadoNube(); 
  if(window.currentUser && window.db && docId) { await window.deleteDoc(window.doc(window.db, "users", window.currentUser.uid, "days", window.getTodayKey(), "meals", docId)); window.cargarHistorialYCheckins(window.currentUser.uid); } 
};
window.eliminarEntrenoNube = async (docId, cals, nombre, btnElement) => { 
  if(!confirm("¿Eliminar del historial?")) return; 
  totalQuemadas = Math.max(0, totalQuemadas - cals); btnElement.closest('li')?.remove(); window.actualizarDashboard(); window.guardarEstadoNube(); 
  if(window.currentUser && window.db && docId) { await window.deleteDoc(window.doc(window.db, "users", window.currentUser.uid, "days", window.getTodayKey(), "workouts", docId)); window.cargarHistorialYCheckins(window.currentUser.uid); } 
};

window.registrarComidaNube = async (cal, prot, carb, gras, nombreDisplay) => { 
  totalCalorias += cal; totalProt += prot; totalCarb += carb; totalGrasa += gras; await window.guardarEstadoNube(); window.actualizarDashboard(); let docId = null; 
  if(window.currentUser && window.db) { const d = await window.addDoc(window.collection(window.db, "users", window.currentUser.uid, "days", window.getTodayKey(), "meals"), { nombre: nombreDisplay, cal, prot, carb, gras, timestamp: Date.now() }); docId = d.id; } 
  window.renderizarComidaEnUI(nombreDisplay, cal, prot, carb, gras, docId); document.querySelector('[data-target="page-dashboard"]')?.click(); if(window.currentUser) window.cargarHistorialYCheckins(window.currentUser.uid);
};

window.registrarEntrenoNube = async (nombre, sets, weight, rpe, cals = 0) => { 
  totalQuemadas += cals; await window.guardarEstadoNube(); window.actualizarDashboard(); let docId = null; 
  if(window.currentUser && window.db) { const d = await window.addDoc(window.collection(window.db, "users", window.currentUser.uid, "days", window.getTodayKey(), "workouts"), { nombre, sets, weight, rpe, cals, timestamp: Date.now() }); docId = d.id; } 
  window.renderizarEntrenoEnUI(nombre, sets, weight, rpe, cals, docId); if(window.currentUser) window.cargarHistorialYCheckins(window.currentUser.uid);
};

window.renderizarComidaEnUI = (nombre, cal, prot, carb, gras, docId = null) => { const l = document.getElementById('lista-comidas'); if(!l) return; const li = document.createElement('li'); if(docId) li.setAttribute('data-id', docId); li.innerHTML = `<span style="color:#fff; font-weight:800; font-size:14px;">${nombre}</span><button class="btn-delete-item" style="background:none; border:none; color:var(--danger); font-size:14px; cursor:pointer; float:right;" onclick="window.eliminarComidaNube('${docId}', ${cal}, ${prot}, ${carb}, ${gras}, '${nombre.replace(/'/g, "\\'")}', this)">🗑️</button><br><span style="color: #9ca3af; font-size: 11px; margin-top:5px; display:block;">🔥 ${cal} kcal &nbsp;|&nbsp; <span style="color:#ff3366;">P: ${prot}g</span> &nbsp;|&nbsp; <span style="color:#00e5ff;">C: ${carb}g</span> &nbsp;|&nbsp; <span style="color:#ffaa00;">G: ${gras}g</span></span>`; l.appendChild(li); };
window.renderizarEntrenoEnUI = (nombre, sets, weight, rpe, cals = 0, docId = null) => { const l = document.getElementById('lista-entrenos'); if(!l) return; const li = document.createElement('li'); if(docId) li.setAttribute('data-id', docId); li.innerHTML = `<span style="color:#fff; font-weight:800; font-size:14px;">${nombre.toUpperCase()}</span><button class="btn-delete-item" style="background:none; border:none; color:var(--danger); font-size:14px; cursor:pointer; float:right;" onclick="window.eliminarEntrenoNube('${docId}', ${cals}, '${nombre.replace(/'/g, "\\'")}', this)">🗑️</button><br><span style="color: #9ca3af; font-size: 11px; margin-top:5px; display:flex; gap:10px; align-items:center;"><span>🏋️ ${sets}</span>${weight>0?`<span>Peso Máx: ${weight} kg</span>`:''} <span style="color:#ffaa00; font-weight:800; background:rgba(255,170,0,0.1); padding:2px 6px; border-radius:4px;">🔥 ~${cals} kcal</span></span>`; l.appendChild(li); };

window.cargarRegistrosDelDia = async (uid) => { const hoyKey = window.getTodayKey(); const listaComidas = document.getElementById('lista-comidas'); if(listaComidas) { listaComidas.innerHTML = ''; const snapshot = await window.getDocs(window.collection(window.db, "users", uid, "days", hoyKey, "meals")); snapshot.forEach(docSnap => { const i = docSnap.data(); window.renderizarComidaEnUI(i.nombre, i.cal, i.prot, i.carb, i.gras, docSnap.id); }); } const listaEntrenos = document.getElementById('lista-entrenos'); if(listaEntrenos) { listaEntrenos.innerHTML = ''; const snapshot = await window.getDocs(window.collection(window.db, "users", uid, "days", hoyKey, "workouts")); snapshot.forEach(docSnap => { const i = docSnap.data(); window.renderizarEntrenoEnUI(i.nombre, i.sets, i.weight, i.rpe, i.cals || 0, docSnap.id); }); } };

window.cargarHistorialYCheckins = async (uid) => {
  const histContainer = document.getElementById('historial-container'); const chkContainer = document.getElementById('checkin-history-container'); const hoyKey = window.getTodayKey();
  if(chkContainer && window.db) { chkContainer.innerHTML = '<p style="text-align:center; font-size:12px; color:#9ca3af;">Cargando check-ins...</p>'; const q = window.query(window.collection(window.db, "users", uid, "checkins"), window.orderBy("timestamp", "desc"), window.limit(15)); const snaps = await window.getDocs(q); let html = ''; let historialPesos = []; snaps.forEach(d => { let data = d.data(); historialPesos.push(data); html += `<div style="background:#111827; padding:12px; margin-bottom:10px; border-radius:8px; border-left:3px solid #ffaa00; display:flex; justify-content:space-between; align-items:center;"><span style="color:#00e5ff; font-weight:800; font-size:12px;">📅 ${data.fecha}</span><span style="color:#fff; font-weight:900; font-size:14px;">⚖️ ${data.peso} kg</span></div>`; }); chkContainer.innerHTML = html || '<p style="text-align:center; font-size:12px; color:#9ca3af;">No hay check-ins registrados.</p>'; if(historialPesos.length > 0) window.dibujarGraficoPerfil(historialPesos); }
  if(histContainer && window.db) {
    histContainer.innerHTML = '<p style="text-align:center; font-size:12px; color:#9ca3af;">Sincronizando jornada táctica...</p>';
    try {
      const mealsSnap = await window.getDocs(window.collection(window.db, "users", uid, "days", hoyKey, "meals")); const workoutsSnap = await window.getDocs(window.collection(window.db, "users", uid, "days", hoyKey, "workouts")); let itemsHoy = [];
      mealsSnap.forEach(m => { let data = m.data(); itemsHoy.push({ tipo: 'comida', nombre: data.nombre, detalle: `🔥 ${data.cal} kcal | P:${data.prot}g C:${data.carb}g G:${data.gras}g` }); });
      workoutsSnap.forEach(w => { let data = w.data(); itemsHoy.push({ tipo: 'entreno', nombre: data.nombre.toUpperCase(), detalle: `${data.sets} | 🔥 ${data.cals || 0} kcal` }); });
      let htmlJornada = `<div class="history-day"><div class="history-day-header" style="cursor:default;"><span>📅 Jornada Actual: ${hoyKey}</span> <span style="color:var(--primary); font-size:11px;">Sincronizado 🟢</span></div><div class="history-day-content" style="display:block; background:rgba(0,0,0,0.2); padding:15px;">`;
      if(itemsHoy.length === 0) { htmlJornada += `<p style="font-size:12px; color:#9ca3af; text-align:center; margin:0;">Sin registros hoy.</p>`; } else { itemsHoy.forEach(i => { htmlJornada += `<div style="margin-top:10px; padding-bottom:10px; border-bottom:1px solid rgba(255,255,255,0.05);"><b style="color:${i.tipo === 'entreno' ? '#00e5ff' : '#ff3366'}; font-size:13px;">${i.tipo === 'entreno' ? '🏋️' : '🍏'} ${i.nombre}</b><br><span style="font-size:11px; color:#9ca3af; display:block; margin-top:4px;">${i.detalle}</span></div>`; }); }
      htmlJornada += `</div></div>`;
      const qOld = window.query(window.collection(window.db, "users", uid, "history"), window.orderBy("timestamp", "desc"), window.limit(30)); const snapsOld = await window.getDocs(qOld); let agrupadoOld = {};
      snapsOld.forEach(d => { let data = d.data(); if(data.date !== hoyKey) { if(!agrupadoOld[data.date]) agrupadoOld[data.date] = []; agrupadoOld[data.date].push(data); } }); let htmlOld = '';
      for(const [fecha, items] of Object.entries(agrupadoOld)) { let itemsHtml = items.map(i => `<div style="margin-top:10px; padding-bottom:10px; border-bottom:1px solid rgba(255,255,255,0.05);"><b style="color:${i.tipo === 'entreno' ? '#00e5ff' : '#ff3366'}; font-size:13px;">${i.tipo === 'entreno' ? '🏋️' : '🍏'} ${i.nombre}</b><br><span style="font-size:11px; color:#9ca3af; display:block; margin-top:4px;">${i.detalle}</span></div>`).join(''); htmlOld += `<div class="history-day"><div class="history-day-header" onclick="const content = this.nextElementSibling; content.style.display = content.style.display === 'block' ? 'none' : 'block';"><span>📅 Jornada: ${fecha}</span> <span style="color:#fff;">▼</span></div><div class="history-day-content">${itemsHtml}</div></div>`; }
      histContainer.innerHTML = htmlJornada + htmlOld;
    } catch(e) { histContainer.innerHTML = '<p style="font-size:12px; color:#ff3366;">Error al sincronizar.</p>'; }
  }
};

window.borrarHistorialJornadas = async () => { if(!confirm("¿Borrar TODO el historial de jornadas de días anteriores?")) return; const q = window.query(window.collection(window.db, "users", window.currentUser.uid, "history")); const snaps = await window.getDocs(q); snaps.forEach(async (d) => await window.deleteDoc(d.ref)); window.showToast('🧹 Historial de jornadas borrado.'); window.cargarHistorialYCheckins(window.currentUser.uid); };
window.borrarHistorialCheckins = async () => { if(!confirm("¿Borrar TODOS los check-ins de peso?")) return; const q = window.query(window.collection(window.db, "users", window.currentUser.uid, "checkins")); const snaps = await window.getDocs(q); snaps.forEach(async (d) => await window.deleteDoc(d.ref)); window.showToast('🧹 Check-ins borrados.'); window.cargarHistorialYCheckins(window.currentUser.uid); };

// 9. COFRADÍA Y MURO (CON AUTO-LIMPIEZA DE ENVIADAS Y COMENTARIOS)
window.cargarModuloSocialCompleto = () => {
  const root = document.getElementById('social-tab-content-root'); if(!root) return;
  root.innerHTML = `<div class="card" style="margin-bottom: 20px;"><h4 style="font-size: 12px; color: #00e5ff; text-transform: uppercase; font-weight: 800; letter-spacing: 1px; margin-bottom: 12px;">👥 Reclutar Amigos</h4><div style="display:flex; gap:8px; margin-bottom:12px;"><input type="text" id="input-search-friend" class="neon-input" placeholder="Apodo exacto..." style="font-size:12px; padding:12px;"><button id="btn-search-friend" class="btn btn-primary" style="width:auto; margin-top:0; padding:12px 20px; font-size:12px;">Buscar</button></div><div id="friend-search-result"></div></div><div class="card" style="margin-bottom: 20px;"><h5 style="font-size: 11px; color: #ffaa00; text-transform: uppercase; font-weight: 800; margin-bottom: 8px;">📩 Solicitudes Entrantes</h5><div id="friend-requests-list" style="font-size:12px; color:#9ca3af; margin-bottom:15px;">Sin solicitudes.</div><h5 style="font-size: 11px; color: #ff3366; text-transform: uppercase; font-weight: 800; margin-bottom: 8px;">🚀 Solicitudes Enviadas</h5><div id="friend-sent-list" style="font-size:12px; color:#9ca3af; margin-bottom:15px;">Ninguna invitación.</div><h5 style="font-size: 11px; color: #00e5ff; text-transform: uppercase; font-weight: 800; margin: 15px 0 8px 0;">⚔️ Cofradía Activa</h5><div id="my-friends-list" style="font-size:12px; color:#9ca3af;">No hay aliados.</div></div><div class="card" style="margin-top: 15px;"><h4 style="font-size: 12px; color: #ffaa00; text-transform: uppercase; font-weight: 800; letter-spacing: 1px; margin-bottom: 10px;">📰 Muro Privado</h4><div style="background: rgba(0,0,0,0.5); padding: 12px; border-radius: 12px; margin-bottom: 20px; border: 1px solid rgba(255,255,255,0.05);"><textarea id="social-post-text" class="neon-input" placeholder="Escribe un logro..." style="height: 60px; font-size:12px; resize:none; border:none; box-shadow:none;"></textarea><button id="btn-publish-social" class="btn btn-primary" style="padding: 10px; font-size:12px; margin-top:8px;">📢 Publicar Logro</button></div><div id="social-feed-container">Cargando muro...</div></div>`;
  document.getElementById('btn-search-friend')?.addEventListener('click', async () => { const val = document.getElementById('input-search-friend').value.trim().toLowerCase(); const resBox = document.getElementById('friend-search-result'); if(!val) return; resBox.innerHTML = '<p style="font-size:11px; color:#9ca3af;">Rastreando...</p>'; try { const q = window.query(window.collection(window.db, "users"), window.where("nickname_lower", "==", val)); const snap = await window.getDocs(q); if(snap.empty) { resBox.innerHTML = '<p style="font-size:11px; color:#ff3366;">❌ Aliado no encontrado.</p>'; return; } const friendDocId = snap.docs[0].id; const friendData = snap.docs[0].data(); if(friendDocId === window.currentUser.uid) { resBox.innerHTML = '<p style="font-size:11px; color:#ffaa00;">⚠️ Eres tú mismo.</p>'; return; } resBox.innerHTML = `<div style="background:rgba(0,229,255,0.1); border:1px solid rgba(0,229,255,0.3); padding:10px; border-radius:10px; display:flex; justify-content:space-between; align-items:center;"><div><b style="color:#fff; font-size:14px;">${friendData.nickname}</b><br><span style="font-size:10px; color:#ffaa00; text-transform:uppercase;">${friendData.currentRankName || 'Ashigaru'}</span></div><button id="btn-send-req" class="btn btn-warning" style="width:auto; margin-top:0; padding:6px 12px; font-size:10px;">+ Enviar</button></div>`; document.getElementById('btn-send-req').onclick = async () => { try { await window.addDoc(window.collection(window.db, "users", friendDocId, "friend_requests"), { fromUid: window.currentUser.uid, fromNickname: userProfile.nickname, status: "pendiente", timestamp: Date.now() }); await window.setDoc(window.doc(window.db, "users", window.currentUser.uid, "sent_requests", friendDocId), { toUid: friendDocId, toNickname: friendData.nickname, status: "pendiente", timestamp: Date.now() }); window.showToast("✅ Invitación enviada."); resBox.innerHTML = ''; window.cargarSolicitudesYAmigosSocial(); } catch(e) { window.showToast("❌ Error al enviar."); } }; } catch(err) { resBox.innerHTML = '<p style="font-size:11px; color:#ff3366;">Error del servidor.</p>'; } });
  document.getElementById('btn-publish-social')?.addEventListener('click', async () => { const txt = document.getElementById('social-post-text').value.trim(); if(!txt) return; try { await window.addDoc(window.collection(window.db, "social_posts"), { uid: window.currentUser.uid, author: userProfile.nickname, rango: currentRankName, avatarStyle: userProfile.avatarStyle, content: txt, timestamp: Date.now() }); document.getElementById('social-post-text').value = ''; window.showToast("📢 ¡Voz alzada!"); window.cargarMuroSocialPrivado(); } catch(e) { window.showToast("❌ Error al publicar."); } });
  window.cargarSolicitudesYAmigosSocial(); window.cargarMuroSocialPrivado();
};

window.cargarSolicitudesYAmigosSocial = async () => {
  if(!window.currentUser || !window.db) return; const reqContainer = document.getElementById('friend-requests-list'); const sentContainer = document.getElementById('friend-sent-list'); const friendsContainer = document.getElementById('my-friends-list');
  try {
    const friendsSnap = await window.getDocs(window.collection(window.db, "users", window.currentUser.uid, "friends")); let friendHtml = ''; let friendUids = []; friendsSnap.forEach(d => { let f = d.data(); friendUids.push(f.friendUid); friendHtml += `<div style="background:rgba(0,229,255,0.05); border:1px solid rgba(0,229,255,0.2); padding:10px; border-radius:10px; margin-bottom:8px; display:flex; justify-content:space-between; align-items:center;"><span style="font-size:14px; font-weight:800; color:#fff;">⚔️ ${f.friendNickname}</span><div style="display:flex; gap:8px;"><button onclick="window.verPerfilAmigoCompleto('${f.friendUid}')" style="background:rgba(0,229,255,0.1); color:#00e5ff; border:1px solid #00e5ff; padding:5px 10px; border-radius:6px; font-size:10px; font-weight:bold; cursor:pointer;">Expediente</button><button onclick="window.eliminarAmigo('${d.id}', '${f.friendUid}')" style="background:rgba(255,51,102,0.1); color:#ff3366; border:1px solid #ff3366; padding:5px 10px; border-radius:6px; font-size:10px; font-weight:bold; cursor:pointer;">Eliminar</button></div></div>`; }); if(friendsContainer) friendsContainer.innerHTML = friendHtml || 'Sin aliados.';
    const sentSnap = await window.getDocs(window.collection(window.db, "users", window.currentUser.uid, "sent_requests")); let sentHtml = ''; 
    sentSnap.forEach(async (d) => { let sent = d.data(); if(friendUids.includes(sent.toUid)) { await window.deleteDoc(d.ref); } else { sentHtml += `<div style="background:rgba(255,51,102,0.1); border:1px solid rgba(255,51,102,0.3); padding:10px; border-radius:10px; display:flex; justify-content:space-between; align-items:center; margin-bottom:8px;"><span style="color:#e5e7eb; font-size:12px;">Para: <b>${sent.toNickname}</b></span><span style="color:#ffaa00; font-size:10px; font-weight:800; text-transform:uppercase; background:rgba(0,0,0,0.5); padding:4px 8px; border-radius:6px;">⏳ ${sent.status}</span></div>`; } }); if(sentContainer) sentContainer.innerHTML = sentHtml || 'Ninguna invitación pendiente.';
    const reqSnap = await window.getDocs(window.collection(window.db, "users", window.currentUser.uid, "friend_requests")); let reqHtml = ''; reqSnap.forEach(d => { let req = d.data(); if(req.status === 'pendiente') { reqHtml += `<div style="background:rgba(255,170,0,0.1); border:1px solid rgba(255,170,0,0.3); padding:10px; border-radius:10px; display:flex; justify-content:space-between; align-items:center; margin-bottom:8px;"><span style="font-size:13px; color:#fff;"><b>${req.fromNickname}</b> solicita unirse</span><button onclick="window.aceptarSolicitud('${d.id}', '${req.fromUid}', '${req.fromNickname}')" class="btn btn-primary" style="width:auto; margin:0; padding:6px 12px; font-size:11px; color:#000;">Aceptar</button></div>`; } }); if(reqContainer) reqContainer.innerHTML = reqHtml || 'Sin solicitudes entrantes.';
  } catch(e) {}
};

window.cargarMuroSocialPrivado = async () => {
  const feed = document.getElementById('social-feed-container'); if(!feed || !window.db) return;
  try {
    const friendsSnap = await window.getDocs(window.collection(window.db, "users", window.currentUser.uid, "friends")); let allowedUids = [window.currentUser.uid]; friendsSnap.forEach(f => allowedUids.push(f.data().friendUid));
    const q = window.query(window.collection(window.db, "social_posts"), window.orderBy("timestamp", "desc"), window.limit(30)); const snaps = await window.getDocs(q); let html = '';
    for(let d of snaps.docs) {
      let post = d.data(); 
      if(allowedUids.includes(post.uid)) { 
        const delBtn = post.uid === window.currentUser.uid ? `<button onclick="window.borrarPostSocial('${d.id}')" style="background:rgba(0,0,0,0.5); border:1px solid #ff3366; color:#ff3366; border-radius:6px; padding:3px 6px; cursor:pointer; font-size:10px; position:absolute; right:15px; top:15px; transition:0.2s;">🗑️</button>` : ''; 
        let commentsHtml = ''; 
        try { const cSnap = await window.getDocs(window.query(window.collection(window.db, "social_posts", d.id, "comments"), window.orderBy("timestamp", "asc"))); cSnap.forEach(cDoc => { const cdata = cDoc.data(); commentsHtml += `<div style="font-size:12px; margin-top:6px; padding:8px; background:rgba(0,0,0,0.4); border-radius:6px;"><b style="color:#00e5ff;">${cdata.author}:</b> <span style="color:#e5e7eb;">${cdata.text}</span></div>`; }); } catch(e){}
        html += `<div class="social-post-card">${delBtn}<div class="social-post-header"><img class="social-post-avatar" src="${window.generarAvatarPorRango(post.author, post.rango || 'Ashigaru', post.avatarStyle || 'bottts')}"><div><b style="color:#fff; font-size:14px; text-transform:uppercase; letter-spacing:1px;">${post.author}</b><br><span style="font-size:9px; color:#00e5ff; font-weight:800; letter-spacing:0.5px;">${post.rango || 'Guerrero'} • ${new Date(post.timestamp).toLocaleDateString()}</span></div></div><div class="social-post-body">${post.content}</div><div style="margin-top:10px; border-top:1px solid rgba(255,255,255,0.05); padding-top:10px;">${commentsHtml}<div style="display:flex; gap:8px; margin-top:10px;"><input type="text" id="comment-input-${d.id}" class="neon-input" style="padding:8px; font-size:12px; margin:0;" placeholder="Comentar..."><button class="btn btn-primary" style="width:auto; padding:8px 15px; margin:0; font-size:11px;" onclick="window.agregarComentario('${d.id}')">💬</button></div></div></div>`; 
      } 
    } feed.innerHTML = html || '<p style="font-size:12px; color:#9ca3af; text-align:center;">Muro silencioso.</p>';
  } catch(e) { feed.innerHTML = '<p style="font-size:12px; color:#ff3366;">Error cargando muro privado.</p>'; }
};

window.borrarPostSocial = async (postId) => { if(!confirm('¿Borrar mensaje del muro?')) return; await window.deleteDoc(window.doc(window.db, "social_posts", postId)); window.showToast('🗑️ Eliminado'); window.cargarMuroSocialPrivado(); };
window.agregarComentario = async (postId) => { const inp = document.getElementById(`comment-input-${postId}`); const text = inp.value.trim(); if(!text) return; try { await window.addDoc(window.collection(window.db, "social_posts", postId, "comments"), { author: userProfile.nickname, text: text, timestamp: Date.now() }); inp.value = ''; window.cargarMuroSocialPrivado(); } catch(e) { window.showToast("❌ Error comentando."); } };
window.aceptarSolicitud = async (reqDocId, fromUid, fromNickname) => { const friendsRef = window.collection(window.db, "users", window.currentUser.uid, "friends"); const checkDup = await window.getDocs(window.query(friendsRef, window.where("friendUid", "==", fromUid))); if(checkDup.empty) { await window.addDoc(friendsRef, { friendUid: fromUid, friendNickname: fromNickname, timestamp: Date.now() }); await window.addDoc(window.collection(window.db, "users", fromUid, "friends"), { friendUid: window.currentUser.uid, friendNickname: userProfile.nickname, timestamp: Date.now() }); } await window.deleteDoc(window.doc(window.db, "users", window.currentUser.uid, "friend_requests", reqDocId)); window.showToast(`⚔️ ¡Alianza forjada con ${fromNickname}!`); window.cargarSolicitudesYAmigosSocial(); window.cargarMuroSocialPrivado(); };
window.eliminarAmigo = async (friendDocId, friendUid) => { if(!confirm("¿Cortar el lazo con este guerrero?")) return; await window.deleteDoc(window.doc(window.db, "users", window.currentUser.uid, "friends", friendDocId)); const reciprocalQuery = window.query(window.collection(window.db, "users", friendUid, "friends"), window.where("friendUid", "==", window.currentUser.uid)); const recSnap = await window.getDocs(reciprocalQuery); recSnap.forEach(async (rDoc) => { await window.deleteDoc(rDoc.ref); }); window.showToast("🗑️ Vínculo roto."); window.cargarSolicitudesYAmigosSocial(); window.cargarMuroSocialPrivado(); };

// --- 10. ALIMENTACIÓN, PLANES Y ORÁCULO DE NUTRICIÓN ---
let oracleDB = []; let exercisesDB = []; let weeklyPlan = []; let selectedDayIndex = 0; let activeAllergies = []; let dynamicDays = [];
async function inicializarBases() { try { const resFood = await fetch('alimentos.json?v=' + Date.now()); if (resFood.ok) oracleDB = await resFood.json(); } catch (e) {} try { const resEx = await fetch('ejercicios.json?v=' + Date.now()); if (!resEx.ok) throw new Error(); exercisesDB = await resEx.json(); } catch (e) {} }
inicializarBases();

const allergyInput = document.getElementById('oracle-allergies-input'); const allergyContainer = document.getElementById('allergy-tags-container');
if(allergyInput) { allergyInput.addEventListener('keypress', (e) => { if(e.key === 'Enter' || e.key === ',') { e.preventDefault(); const val = allergyInput.value.trim().toLowerCase(); if(val && !activeAllergies.includes(val)) { activeAllergies.push(val); window.renderAllergyChips(); } allergyInput.value = ''; } }); }
window.renderAllergyChips = () => { if(!allergyContainer) return; allergyContainer.innerHTML = ''; activeAllergies.forEach((allergy, index) => { const chip = document.createElement('div'); chip.className = 'allergy-chip'; chip.innerHTML = `<span>${allergy}</span><span class="allergy-chip-close" onclick="window.removeAllergy(${index})">×</span>`; allergyContainer.appendChild(chip); }); };
window.removeAllergy = index => { activeAllergies.splice(index, 1); window.renderAllergyChips(); };

window.calcularFechasSemana = () => { dynamicDays = []; const date = new Date(); const dayNames = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb']; const monthNames = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']; for(let i=0; i<7; i++) { let d = new Date(date); d.setDate(d.getDate() + i); dynamicDays.push({ index: i, shortName: dayNames[d.getDay()], fullName: `${dayNames[d.getDay()]}, ${d.getDate()} ${monthNames[d.getMonth()]}` }); } };

document.getElementById('btn-generar-plan')?.addEventListener('click', () => { if (oracleDB.length === 0) { window.showToast("⚠️ Sincronizando alimentos..."); return; } window.calcularFechasSemana(); window.generarPlanSemanal(); document.getElementById('oracle-form-card').style.display = 'none'; document.getElementById('plan-resultado').style.display = 'block'; window.showToast('🤖 Plan clínico generado.'); });

window.seleccionarDiaPlan = index => { selectedDayIndex = index; document.querySelectorAll('.day-chip').forEach(btn => btn.classList.remove('active')); document.querySelector(`.day-chip[data-day="${index}"]`)?.classList.add('active'); const ph = document.getElementById('plan-date-header'); if(ph) ph.innerText = dynamicDays[index].fullName; window.renderizarDiaSeleccionado(); };

window.generarPlanSemanal = () => { 
  weeklyPlan = []; const distribution = [ { tipo: 'desayuno', cals: metaCalorias * 0.30 }, { tipo: 'almuerzo', cals: metaCalorias * 0.40 }, { tipo: 'cena', cals: metaCalorias * 0.30 } ]; 
  for(let i=0; i<7; i++) { let dayMeals = distribution.map(slot => window.obtenerComidaAlgoritmo(slot.tipo, slot.cals, [])); weeklyPlan.push(dayMeals); } 
  window.renderizarSelectoresDias(); window.seleccionarDiaPlan(0); 
};

window.renderizarSelectoresDias = () => { const scrollContainer = document.getElementById('day-selector-container'); if(scrollContainer) { scrollContainer.innerHTML = ''; dynamicDays.forEach(day => { scrollContainer.innerHTML += `<button class="day-chip ${day.index === selectedDayIndex ? 'active' : ''}" data-day="${day.index}" onclick="window.seleccionarDiaPlan(${day.index})">${day.shortName}</button>`; }); } };
window.filtrarBaseDatos = (tipo, excludesId) => { let currentDietType = document.getElementById('oracle-diet-type')?.value || 'normal'; let isCeliac = document.getElementById('oracle-celiac')?.checked || false; let isLactose = document.getElementById('oracle-lactose')?.checked || false; let isSibo = document.getElementById('oracle-sibo')?.checked || false; let candidatos = oracleDB.filter(m => { if(m.tipo !== tipo) return false; if(m.dietas && !m.dietas.includes(currentDietType)) return false; if(excludesId && excludesId.includes(m.id)) return false; if(isCeliac && m.glutenFree === false) return false; if(isLactose && m.lactoseFree === false) return false; if(isSibo && m.siboSafe === false) return false; let jsonStr = JSON.stringify(m).toLowerCase(); for(let a of activeAllergies) { if(jsonStr.includes(a)) return false; } return true; }); if(candidatos.length === 0) candidatos = oracleDB.filter(m => m.tipo === tipo); return candidatos; };
window.calcularMacrosPorcion = (comidaBase, targetCals) => { const factor = targetCals / (comidaBase.calBase || 1); let ingredientesAdaptados = (comidaBase.ingredientes || []).map(ing => { let qtyCalculada = ing.baseQty * factor; qtyCalculada = ing.unidad === 'unidades' || ing.unidad === 'scoops' ? parseFloat(qtyCalculada.toFixed(1)) : Math.round(qtyCalculada); return { nombre: ing.nombre, cantidad: qtyCalculada, unidad: ing.unidad }; }); return { id: comidaBase.id, tipo: comidaBase.tipo, name: comidaBase.name, cals: Math.round(comidaBase.calBase * factor), prot: Math.round(comidaBase.prot * factor), carb: Math.round(comidaBase.carb * factor), gras: Math.round(comidaBase.gras * factor), ingredientes: ingredientesAdaptados }; };
window.obtenerComidaAlgoritmo = (tipo, targetCals, excludesId) => { const candidatos = window.filtrarBaseDatos(tipo, excludesId); if(candidatos.length === 0) return { id: 0, tipo: tipo, name: "Sin Opciones", cals: targetCals, prot: 0, carb: 0, gras: 0, ingredientes: [] }; const selected = candidatos[Math.floor(Math.random() * candidatos.length)]; return window.calcularMacrosPorcion(selected, targetCals); };

window.renderizarDiaSeleccionado = () => { 
  const container = document.getElementById('comidas-plan'); if(!container) return; container.innerHTML = ''; const dayMeals = weeklyPlan[selectedDayIndex] || []; 
  dayMeals.forEach((meal, idx) => { let ingredientesHTML = meal.ingredientes.length > 0 ? meal.ingredientes.map(i => `<span style="display:block; margin-bottom:3px; color:#e5e7eb; font-size:12px;">• ${i.cantidad} ${i.unidad} de ${i.nombre}</span>`).join('') : `• Sin ingredientes`; container.innerHTML += `<div class="plan-meal-card"><div class="plan-meal-header"><span class="plan-meal-title">${meal.tipo}</span><button class="btn-swap" onclick="window.abrirMenuReemplazo(${idx})">🔄 Cambiar</button></div><div class="plan-meal-desc"><b style="color:#00e5ff; font-size:14px; display:block; margin-bottom:8px;">${meal.name}</b>${ingredientesHTML}</div><div style="display:flex; justify-content:space-between; align-items:center; margin-top:15px; border-top:1px dashed rgba(255,255,255,0.1); padding-top:10px;"><span class="plan-meal-cals" style="background:transparent; border:none; padding:0;">🔥 ${meal.cals} kcal</span><span style="font-size:11px; color:var(--text-muted); font-weight:800;">P:<span style="color:#ff3366;">${meal.prot}g</span> C:<span style="color:#00e5ff;">${meal.carb}g</span> G:<span style="color:#ffaa00;">${meal.gras}g</span></span></div></div>`; }); 
};

let swapTargetIndex = -1;
window.abrirMenuReemplazo = mealIndex => { swapTargetIndex = mealIndex; const oldMeal = weeklyPlan[selectedDayIndex][mealIndex]; const targetCals = oldMeal.cals; let candidatos = window.filtrarBaseDatos(oldMeal.tipo, [oldMeal.id]); const listContainer = document.getElementById('sheet-swap-list'); if(!listContainer) return; listContainer.innerHTML = ''; if(candidatos.length === 0) { listContainer.innerHTML = `<p style="font-size:12px; color:#ff3366;">No hay opciones.</p>`; } else { for(let i=0; i<candidatos.length; i++) { let opcionEscalada = window.calcularMacrosPorcion(candidatos[i], targetCals); let objData = encodeURIComponent(JSON.stringify(opcionEscalada)); listContainer.innerHTML += `<div class="swap-option-card" onclick="window.confirmarReemplazo('${objData}')"><b style="display:block; color:#fff;">${opcionEscalada.name}</b><span style="font-size:11px; color:var(--primary);">🔥 ${opcionEscalada.cals} kcal | P: ${opcionEscalada.prot}g | C: ${opcionEscalada.carb}g | G: ${opcionEscalada.gras}g</span></div>`; } } window.openSheet('sheet-swap-meal'); };
window.confirmarReemplazo = encodedData => { if(swapTargetIndex > -1) { const newMeal = JSON.parse(decodeURIComponent(encodedData)); weeklyPlan[selectedDayIndex][swapTargetIndex] = newMeal; window.guardarPlanNube(); window.renderizarDiaSeleccionado(); window.closeSheet(); window.showToast(`✅ Actualizado.`); } };

window.guardarPlanNube = async () => { if(!weeklyPlan || weeklyPlan.length === 0) return; try { await window.setDoc(window.doc(window.db, "users", window.currentUser.uid, "weekly_plan", "current"), { plan: JSON.stringify(weeklyPlan), date: Date.now() }); window.showToast("💾 Plan guardado en la nube."); } catch(e) { window.showToast("❌ Error al guardar."); } };
window.recuperarPlanesGuardados = async () => { if(!window.currentUser || !window.db) return; try { const planSnap = await window.getDoc(window.doc(window.db, "users", window.currentUser.uid, "weekly_plan", "current")); if(planSnap.exists()) { weeklyPlan = JSON.parse(planSnap.data().plan); window.calcularFechasSemana(); document.getElementById('oracle-form-card').style.display = 'none'; document.getElementById('plan-resultado').style.display = 'block'; window.renderizarSelectoresDias(); window.seleccionarDiaPlan(0); } } catch(e) {} };

window.generarListaCompras = () => { const ul = document.getElementById('lista-compras-ui'); if(!ul) return; let listaConsolidada = {}; weeklyPlan.forEach(dia => { dia.forEach(comida => { comida.ingredientes.forEach(ing => { let key = `${ing.nombre} (${ing.unidad})`; listaConsolidada[key] = (listaConsolidada[key] || 0) + ing.cantidad; }); }); }); ul.innerHTML = ''; for (let key in listaConsolidada) { let rawQty = listaConsolidada[key]; let qtyDisplay = key.includes('unidades') || key.includes('scoops') ? rawQty.toFixed(1) : Math.round(rawQty); let match = key.match(/(.*) \((.*)\)/); let nombreLimpio = match ? match[1] : key; let unidadLimpia = match ? match[2] : ''; ul.innerHTML += `<li><input type="checkbox" style="accent-color:var(--primary); width:18px; height:18px;"> <span style="flex:1;">${nombreLimpio}</span> <b style="color:var(--primary); font-size:12px; background:rgba(0,229,255,0.1); padding:4px 8px; border-radius:6px;">${qtyDisplay} ${unidadLimpia}</b></li>`; } window.openSheet('sheet-compras'); };

document.getElementById('btn-add-planned')?.addEventListener('click', () => { if(!weeklyPlan || weeklyPlan.length === 0) { window.showToast('⚠️ Genera el oráculo semanal primero.'); return; } const listContainer = document.getElementById('sheet-planned-list'); if(!listContainer) return; listContainer.innerHTML = ''; const todaysPlan = weeklyPlan[0]; todaysPlan.forEach(meal => { let objData = encodeURIComponent(JSON.stringify(meal)); listContainer.innerHTML += `<div class="swap-option-card" onclick="window.registrarComidaPlaneada('${objData}')"><span style="font-size:10px; color:var(--primary); font-weight:800; text-transform:uppercase;">${meal.tipo}</span><b style="display:block; color:#fff; margin-top:4px;">${meal.name}</b><span>🔥 ${meal.cals} kcal | P: ${meal.prot}g | C: ${meal.carb}g | G: ${meal.gras}g</span></div>`; }); window.openSheet('sheet-planned-meals'); });
window.registrarComidaPlaneada = async encodedData => { try { const meal = JSON.parse(decodeURIComponent(encodedData)); let nombreFinal = `[${meal.tipo.charAt(0).toUpperCase() + meal.tipo.slice(1)}] ${meal.name}`; await window.registrarComidaNube(meal.cals, meal.prot, meal.carb, meal.gras, nombreFinal); window.closeSheet(); window.showToast(`✅ Menú registrado.`); } catch(e) { window.closeSheet(); } };

// ESCÁNER Y BUSCADOR OPENFOODFACTS
let html5QrCode = null;
document.getElementById('btn-foto')?.addEventListener('click', () => { window.openSheet('sheet-scanner'); if (!html5QrCode) html5QrCode = new Html5Qrcode("qr-reader"); const config = { fps: 10, qrbox: { width: 250, height: 250 }, aspectRatio: 1.0 }; html5QrCode.start({ facingMode: "environment" }, config, window.onScanSuccess, () => {}).catch(err => { window.showToast("⚠️ Da permisos a la cámara."); }); });
window.closeScanner = () => { if (html5QrCode && html5QrCode.isScanning) { html5QrCode.stop().then(() => { html5QrCode.clear(); }).catch(e => console.error(e)); } window.closeSheet(); };
window.onScanSuccess = async decodedText => { if (html5QrCode && html5QrCode.isScanning) { await html5QrCode.stop(); } window.closeScanner(); window.showToast(`🔍 Escaneando...`); try { const res = await fetch(`https://world.openfoodfacts.org/api/v0/product/${decodedText}.json`); const data = await res.json(); if (data.status === 1) { const p = data.product; if(!p.nutriments || !p.nutriments['energy-kcal_100g']) { window.showToast('⚠️ Sin info.'); return; } let brand = p.brands ? ` (${p.brands.split(',')[0]})` : ''; let nombre = `${p.product_name || 'Producto'}${brand}`; let cal100 = Math.round(p.nutriments['energy-kcal_100g']); let prot100 = Math.round(p.nutriments['proteins_100g'] || 0); let carb100 = Math.round(p.nutriments['carbohydrates_100g'] || 0); let gras100 = Math.round(p.nutriments['fat_100g'] || 0); window.currentSearchFoodBase = { cal: cal100, prot: prot100, carb: carb100, gras: gras100 }; document.getElementById('food-selected-name').innerText = nombre; document.getElementById('food-results-list').innerHTML = ''; document.getElementById('edit-qty').value = '100'; document.getElementById('edit-unit').value = '1'; window.recalcularMacros(); document.getElementById('food-custom-section').style.display = 'block'; window.openSheet('sheet-add-food'); } else { window.showToast('❌ No encontrado.'); } } catch (err) { window.showToast('⚠️ Error conexión.'); } };

window.currentSearchFoodBase = null;
const fallbackDB = [ { product_name: "Yogurt Protein", brands: "Soprole", nutriments: { 'energy-kcal_100g': 55, 'proteins_100g': 8, 'carbohydrates_100g': 5, 'fat_100g': 0 } }, { product_name: "Avena", brands: "Quaker", nutriments: { 'energy-kcal_100g': 370, 'proteins_100g': 13, 'carbohydrates_100g': 60, 'fat_100g': 7 } } ];
document.getElementById('btn-abrir-manual')?.addEventListener('click', () => { document.getElementById('food-search').value = ''; document.getElementById('food-results-list').innerHTML = ''; document.getElementById('food-custom-section').style.display = 'none'; window.openSheet('sheet-add-food'); });
document.getElementById('btn-trigger-search')?.addEventListener('click', async () => { const queryVal = document.getElementById('food-search').value.trim().toLowerCase(); const c = document.getElementById('food-results-list'); const loader = document.getElementById('food-loading'); if(!queryVal) return; c.innerHTML = ''; loader.style.display = 'block'; try { const res = await fetch(`https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(queryVal)}&search_simple=1&action=process&json=1&page_size=15`); if (!res.ok) throw new Error('Fallo'); const data = await res.json(); loader.style.display = 'none'; if(!data.products || data.products.length === 0) throw new Error("0"); window.renderizarResultadosBusqueda(data.products, c); } catch (error) { loader.style.display = 'none'; const resultadosLocales = fallbackDB.filter(p => p.product_name.toLowerCase().includes(queryVal) || p.brands.toLowerCase().includes(queryVal)); if(resultadosLocales.length > 0) { window.renderizarResultadosBusqueda(resultadosLocales, c); window.showToast('⚠️ Base local activada.'); } else { c.innerHTML = `<div style="font-size:12px; color:#ff3366; text-align:center; margin-top:10px;">❌ Cero coincidencias.</div>`; } } });

window.renderizarResultadosBusqueda = (productos, contenedor) => { productos.forEach(p => { if(!p.nutriments || p.nutriments['energy-kcal_100g'] == null) return; const d = document.createElement('div'); d.className = 'search-item'; let brand = p.brands ? ` (${p.brands.split(',')[0]})` : ''; let nombre = `${p.product_name || 'Producto'}${brand}`; let cal100 = Math.round(p.nutriments['energy-kcal_100g']); let prot100 = Math.round(p.nutriments['proteins_100g'] || 0); let carb100 = Math.round(p.nutriments['carbohydrates_100g'] || 0); let gras100 = Math.round(p.nutriments['fat_100g'] || 0); d.innerHTML = `<div style="display:flex; flex-direction:column;"><span>${nombre}</span><span style="font-size:9px; color:var(--text-muted);">P:${prot100}g C:${carb100}g G:${gras100}g</span></div><span style="color:var(--primary); font-weight:800;">${cal100} kcal</span>`; d.addEventListener('click', () => { window.currentSearchFoodBase = { cal: cal100, prot: prot100, carb: carb100, gras: gras100 }; document.getElementById('food-selected-name').innerText = nombre; document.getElementById('food-results-list').innerHTML = ''; document.getElementById('edit-qty').value = '100'; document.getElementById('edit-unit').value = '1'; window.recalcularMacros(); document.getElementById('food-custom-section').style.display = 'block'; }); contenedor.appendChild(d); }); };
document.getElementById('edit-qty')?.addEventListener('input', () => window.recalcularMacros()); document.getElementById('edit-unit')?.addEventListener('change', () => window.recalcularMacros());
window.recalcularMacros = () => { if(window.currentSearchFoodBase) { let q = parseFloat(document.getElementById('edit-qty').value) || 0; let m = parseFloat(document.getElementById('edit-unit').value) || 1; let factor = (q * m) / 100; document.getElementById('edit-cal').value = Math.round(window.currentSearchFoodBase.cal * factor); document.getElementById('edit-prot').value = Math.round(window.currentSearchFoodBase.prot * factor); document.getElementById('edit-carb').value = Math.round(window.currentSearchFoodBase.carb * factor); document.getElementById('edit-gras').value = Math.round(window.currentSearchFoodBase.gras * factor); } };
document.getElementById('btn-confirm-food-final')?.addEventListener('click', async function() { if (this.disabled) return; this.disabled = true; let mt = document.getElementById('food-meal-time').value; let n = document.getElementById('food-selected-name').innerText || "Alimento"; let c = parseInt(document.getElementById('edit-cal').value)||0; let p = parseInt(document.getElementById('edit-prot').value)||0; let cb = parseInt(document.getElementById('edit-carb').value)||0; let g = parseInt(document.getElementById('edit-gras').value)||0; let qtyVal = document.getElementById('edit-qty').value; let unitSelect = document.getElementById('edit-unit'); let unitText = unitSelect.options[unitSelect.selectedIndex].text.split(' ')[0]; if(!c && !p) { window.showToast('⚠️ Ingresa cantidad.'); this.disabled = false; return; } let nombreFinalRegistro = `${n} (${qtyVal} ${unitText})`; await window.registrarComidaNube(c, p, cb, g, `[${mt}] ${nombreFinalRegistro}`); window.closeSheet(); window.showToast(`✅ Alimento guardado.`); this.disabled = false; });

if ('serviceWorker' in navigator) { window.addEventListener('load', () => { navigator.serviceWorker.register('sw.js').catch(console.log); }); }
